/-
# EXP-048: finite Electronic Mail as a static Bayesian/Epistemic bridge

The example shares one finite law on endpoint worlds between the Bayesian type
prior and the epistemic partition. It tests whether the pinned results observe
anything that requires a Protocol execution history.
-/

import GameTheory.Core.BayesianEquilibrium
import GameTheory.Epistemic.Approximate
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum

noncomputable section

namespace GameTheory.Experimental.PostArchitecture.ElectronicMail

open GameTheory GameTheory.Math.Probability GameTheory.Epistemic

set_option backward.isDefEq.respectTransparency false in
/-- Finite endpoint worlds for the email exchange. -/
inductive EmailWorld where
  | noMessage
  | onlyFirst
  | bothConfirmed
deriving DecidableEq, Repr, Fintype

set_option backward.isDefEq.respectTransparency false in
/-- A player's private email observation. -/
inductive EmailView where
  | quiet
  | message
deriving DecidableEq, Repr, Fintype

set_option backward.isDefEq.respectTransparency false in
/-- The action in the coordinated-attack game. -/
inductive EmailAction where
  | stay
  | attack
deriving DecidableEq, Repr, Fintype

open EmailWorld EmailView EmailAction

private theorem EmailWorld_univ :
    (Finset.univ : Finset EmailWorld) =
      {noMessage, onlyFirst, bothConfirmed} := by
  ext world
  cases world <;> simp

/-- One canonical uniform law on the three endpoint worlds. -/
def worldPrior : FinDist EmailWorld :=
  FinDist.ofWeights (fun _ => (1 / 3 : ℝ))
    (fun _ => by norm_num)
    (by
      rw [EmailWorld_univ, Finset.sum_const]
      rw [show ({noMessage, onlyFirst, bothConfirmed} :
        Finset EmailWorld).card = 3 by decide]
      norm_num)

/-- Player observations generated by the endpoint worlds. -/
def viewOf : EmailWorld → Bool → EmailView
  | noMessage, _ => quiet
  | onlyFirst, true => message
  | onlyFirst, false => quiet
  | bothConfirmed, _ => message

/-- The type profile associated with a world. -/
def typeProfile (world : EmailWorld) : Bool → EmailView :=
  fun player => viewOf world player

/-- The Bayesian type prior is the pushforward of the same world law used by
the epistemic model. -/
def emailPrior : FinDist (Bool → EmailView) :=
  worldPrior.map typeProfile

/-- The payoff-relevant event: the first message was sent. -/
abbrev attackState (types : Bool → EmailView) : Prop :=
  types true = message

/-- Successful joint attack in the attack state pays one; any other attack
costs two; staying pays zero. -/
def emailPayoff (types : Bool → EmailView)
    (actions : Bool → EmailAction) (player : Bool) : ℝ :=
  if actions player = stay then 0
  else if attackState types ∧
      actions true = attack ∧ actions false = attack then 1
  else -2

/-- The finite Bayesian game induced by the email observations. -/
@[reducible]
def game : BayesianGame Bool where
  Ty _ := EmailView
  Act _ := EmailAction
  prior := emailPrior
  payoff := emailPayoff

/-- Attack exactly when a message is observed. -/
def attackOnMessage : Profile game.signature :=
  fun _ view =>
    match view with
    | quiet => stay
    | message => attack

/-- Player `true`'s deviation: never attack. -/
def trueNeverAttack : game.signature.Strategy true :=
  fun _ => stay

/-- The finite information partition induced by private views. -/
def emailPartition (player : Bool) : InfoPartition EmailWorld where
  cell world := Finset.univ.filter fun other =>
    viewOf other player = viewOf world player
  reflexive world := by simp
  coherent world other hother := by
    ext candidate
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hother ⊢
    rw [hother]

/-- World-level event that the first message was sent. -/
def attackStateEvent : Finset EmailWorld :=
  {onlyFirst, bothConfirmed}

@[simp]
theorem viewOf_noMessage (player : Bool) :
    viewOf noMessage player = quiet := by
  cases player <;> rfl

@[simp]
theorem viewOf_onlyFirst_true :
    viewOf onlyFirst true = message := rfl

@[simp]
theorem viewOf_onlyFirst_false :
    viewOf onlyFirst false = quiet := rfl

@[simp]
theorem viewOf_bothConfirmed (player : Bool) :
    viewOf bothConfirmed player = message := by
  cases player <;> rfl

/-- At the confirmed endpoint, the attack state is mutually believed for every
threshold at most one. -/
theorem bothConfirmed_mem_mutualPBelief_attackStateEvent
    {threshold : ℝ} (hthreshold : threshold ≤ 1) :
    bothConfirmed ∈
      mutualPBelief worldPrior emailPartition threshold attackStateEvent := by
  rw [mem_mutualPBelief_iff]
  intro player
  cases player
  · unfold posterior attackStateEvent
    rw [show (emailPartition false).cell bothConfirmed =
      {bothConfirmed} by decide]
    simp [worldPrior]
    linarith
  · unfold posterior attackStateEvent
    rw [show (emailPartition true).cell bothConfirmed =
      {onlyFirst, bothConfirmed} by decide]
    simp [worldPrior]
    linarith

/-- Above threshold one half, the attack state is not common belief at the
confirmed endpoint. -/
theorem not_commonPBeliefAt_attackStateEvent_bothConfirmed_of_half_lt
    {threshold : ℝ} (hthreshold : (1 / 2 : ℝ) < threshold) :
    ¬ CommonPBeliefAt worldPrior emailPartition threshold
      attackStateEvent bothConfirmed := by
  rintro ⟨witness, hboth, hevident, hmutual⟩
  have honly : onlyFirst ∈ witness := by
    have hbelief := hevident true hboth
    rw [mem_PBelief_iff] at hbelief
    by_contra hnot
    have hposterior :
        posterior worldPrior (emailPartition true) witness bothConfirmed =
          (1 / 2 : ℝ) := by
      unfold posterior worldPrior
      rw [show (emailPartition true).cell bothConfirmed =
        {onlyFirst, bothConfirmed} by decide]
      rw [show {onlyFirst, bothConfirmed} ∩ witness =
        {bothConfirmed} by
          ext world
          cases world <;> simp [hboth, hnot]]
      simp
      norm_num
    linarith
  have hnoMessage : noMessage ∈ witness := by
    have hbelief := hevident false honly
    rw [mem_PBelief_iff] at hbelief
    by_contra hnot
    have hposterior :
        posterior worldPrior (emailPartition false) witness onlyFirst =
          (1 / 2 : ℝ) := by
      unfold posterior worldPrior
      rw [show (emailPartition false).cell onlyFirst =
        {noMessage, onlyFirst} by decide]
      rw [show {noMessage, onlyFirst} ∩ witness = {onlyFirst} by
        ext world
        cases world <;> simp [honly, hnot]]
      simp
      norm_num
    linarith
  have hnoMutual := hmutual hnoMessage
  rw [mem_mutualPBelief_iff] at hnoMutual
  have htrue := hnoMutual true
  have hposterior :
      posterior worldPrior (emailPartition true)
        attackStateEvent noMessage = 0 := by
    unfold posterior worldPrior attackStateEvent
    rw [show (emailPartition true).cell noMessage = {noMessage} by decide]
    simp
  linarith

/-- Under the candidate rule, player `true`'s ex-ante value is negative. -/
theorem expectedUtility_attackOnMessage_true :
    expectedUtility game.utility true
      (game.toForm.play attackOnMessage) = (-1 / 3 : ℝ) := by
  rw [BayesianGame.toForm_play]
  unfold game BayesianGame.utility BayesianGame.actionsOf
  unfold expectedUtility emailPrior
  rw [FinDist.expect_map, FinDist.expect_map, FinDist.expect_eq_sum]
  rw [EmailWorld_univ]
  simp [worldPrior, game, emailPayoff, attackState,
    attackOnMessage, typeProfile, viewOf]
  norm_num

/-- If player `true` deviates to never attacking, its ex-ante value is zero. -/
theorem expectedUtility_trueNeverAttack :
    expectedUtility game.utility true
      (game.toForm.play
        (Profile.update attackOnMessage true trueNeverAttack)) = 0 := by
  rw [BayesianGame.toForm_play]
  unfold game BayesianGame.utility BayesianGame.actionsOf
  unfold expectedUtility emailPrior
  rw [FinDist.expect_map, FinDist.expect_map, FinDist.expect_eq_sum]
  rw [EmailWorld_univ]
  simp [worldPrior, emailPayoff, trueNeverAttack, typeProfile, viewOf]

/-- The attack-on-message rule is not Bayes-Nash, stated through the ordinary
Nash predicate of the canonical direct Bayesian form. -/
theorem attackOnMessage_not_isNash :
    ¬ IsNash game.toForm (euPreference game.utility) attackOnMessage := by
  intro hnash
  rw [isNash_iff] at hnash
  have hdeviation := hnash true trueNeverAttack
  rw [euPreference_apply, expectedUtility_attackOnMessage_true,
    expectedUtility_trueNeverAttack] at hdeviation
  norm_num at hdeviation

end GameTheory.Experimental.PostArchitecture.ElectronicMail
