/-
# EXP-062: intrinsic-game ownership

This hostile slice tests closed-loop configuration and causality while
deliberately omitting probability, utility, compiler, mixed/behavioral, and
Kuhn layers.
-/

import Mathlib.Logic.Equiv.Bool

namespace GameTheory.Experimental.IntrinsicOwnership

universe u

/-- A closed-loop configuration records nature and every agent's decision at
once.  It is not a Protocol history: no temporal order has yet been chosen. -/
structure Config (Nature : Type u) (Agent : Type u)
    (Decision : Agent → Type u) where
  nature : Nature
  decision : (agent : Agent) → Decision agent

/-- The capability-light intrinsic information object under test. -/
structure Model where
  Agent : Type u
  Nature : Type u
  Decision : Agent → Type u
  info : (agent : Agent) → Setoid (Config Nature Agent Decision)

namespace Model

abbrev Configuration (M : Model) :=
  Config M.Nature M.Agent M.Decision

/-- One agent's decision rule, constant on that agent's information classes. -/
structure PureStrategy (M : Model) (agent : M.Agent) where
  act : M.Configuration → M.Decision agent
  respects : ∀ left right,
    (M.info agent).r left right → act left = act right

abbrev PureProfile (M : Model) :=
  (agent : M.Agent) → M.PureStrategy agent

/-- The simultaneous closed-loop equations generated by an intrinsic pure
profile. -/
def IsFixedPoint (M : Model) (profile : M.PureProfile)
    (nature : M.Nature) (decision : (agent : M.Agent) → M.Decision agent) :
    Prop :=
  ∀ agent, decision agent =
    (profile agent).act ⟨nature, decision⟩

/-- Every pure profile and nature state has a unique closed-loop solution. -/
def IsSolvable (M : Model) : Prop :=
  ∀ (profile : M.PureProfile) (nature : M.Nature),
    ∃! decision : (agent : M.Agent) → M.Decision agent,
      M.IsFixedPoint profile nature decision

/-- A configuration-dependent exhaustive order.  The slot count is explicit;
no global finite-player capability is stored in the model. -/
structure Schedule (M : Model) (slots : ℕ) where
  orderAt : M.Configuration → Fin slots ≃ M.Agent

/-- Two configurations choose the same schedule through the current slot. -/
def SamePrefixThrough {M : Model} {slots : ℕ}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) : Prop :=
  ∀ earlier : Fin slots, earlier.1 ≤ slot.1 →
    schedule.orderAt left earlier = schedule.orderAt right earlier

/-- Pinned `configSet` without list encoding: `candidate` lies in the cell of
`reference` determined by the first `count` scheduled agents. -/
def PrefixCell {M : Model} {slots : ℕ}
    (schedule : M.Schedule slots) (reference : M.Configuration)
    (count : ℕ) (candidate : M.Configuration) : Prop :=
  ∀ earlier : Fin slots, earlier.1 < count →
    schedule.orderAt candidate earlier = schedule.orderAt reference earlier

/-- Direct comparison of two schedule prefixes is exactly membership in the
configuration-prefix cell used by the pinned intrinsic causality definition. -/
theorem samePrefixThrough_iff_prefixCell {M : Model} {slots : ℕ}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) :
    SamePrefixThrough schedule slot left right ↔
      PrefixCell schedule left (slot.1 + 1) right := by
  constructor
  · intro hprefix earlier hearlier
    exact (hprefix earlier (by omega)).symm
  · intro hcell earlier hearlier
    exact (hcell earlier (by omega)).symm

/-- Nature and every already-made decision agree before the current slot. -/
def AgreeBefore {M : Model} {slots : ℕ}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) : Prop :=
  left.nature = right.nature ∧
    ∀ earlier : Fin slots, earlier.1 < slot.1 →
      left.decision (schedule.orderAt left earlier) =
        right.decision (schedule.orderAt left earlier)

/-- At the current slot, information may depend on nature and predecessor
decisions, but not on a decision scheduled later. -/
def IsCausalWith {M : Model} {slots : ℕ}
    (schedule : M.Schedule slots) : Prop :=
  ∀ (left right : M.Configuration) (slot : Fin slots),
    SamePrefixThrough schedule slot left right →
    AgreeBefore schedule slot left right →
    (M.info (schedule.orderAt left slot)).r left right

end Model

def universalSetoid (α : Type*) : Setoid α where
  r _ _ := True
  iseqv := ⟨fun _ => trivial, fun _ => trivial, fun _ _ => trivial⟩

/-- Two Boolean agents with no information and no temporal order baked into
their decision rules. -/
def trivialModel : Model where
  Agent := Bool
  Nature := Unit
  Decision := fun _ => Bool
  info := fun _ => universalSetoid _

/-- Trivial information is enough for unique closed-loop solvability: every
admissible strategy is constant on the entire configuration space. -/
theorem trivialModel_isSolvable : trivialModel.IsSolvable := by
  intro profile nature
  let seed : (agent : Bool) → trivialModel.Decision agent :=
    fun agent => (profile agent).act ⟨nature, fun _ => false⟩
  refine ⟨seed, ?_, ?_⟩
  · intro agent
    exact (profile agent).respects _ _ trivial
  · intro decision hfixed
    funext agent
    rw [hfixed agent]
    exact (profile agent).respects _ _ trivial

def trivialOrder : trivialModel.Schedule 2 :=
  ⟨fun _ => finTwoEquiv⟩

theorem trivialModel_isCausal :
    Model.IsCausalWith trivialOrder := by
  intro left right slot _ _
  trivial

/-- Agent `false` observes the decision of agent `true`, who is scheduled
later; agent `true` has trivial information. -/
def futureLookingModel : Model where
  Agent := Bool
  Nature := Unit
  Decision := fun _ => Bool
  info
    | false =>
        { r := fun left right => left.decision true = right.decision true
          iseqv :=
            ⟨fun _ => rfl, fun h => h.symm,
              fun hleft hright => hleft.trans hright⟩ }
    | true => universalSetoid _

def allFalse : futureLookingModel.Configuration :=
  ⟨(), fun _ => false⟩

def futureTrue : futureLookingModel.Configuration :=
  ⟨(), fun agent => agent⟩

def futureOrder : futureLookingModel.Schedule 2 :=
  ⟨fun _ => finTwoEquiv⟩

/-- The intrinsic causality predicate detects dependence on a future decision
before any Protocol compiler or execution history exists. -/
theorem futureLookingModel_not_causal :
    ¬ Model.IsCausalWith futureOrder := by
  intro hcausal
  have hinfo := hcausal allFalse futureTrue (0 : Fin 2)
    (by
      intro earlier _
      rfl)
    (by
      constructor
      · rfl
      · intro earlier hearlier
        omega)
  have hinfo' : allFalse.decision true = futureTrue.decision true := hinfo
  have hne : (false : futureLookingModel.Decision true) ≠ true := by
    decide
  exact hne hinfo'

/-! ## Nonconstant schedule validation -/

/-- Three agents: agent zero has trivial information; either later agent may
observe the predecessor decision and the configuration-cell branch that
selected the later order. -/
abbrev branchingConfiguration := Config Unit (Fin 3) (fun _ => Bool)

abbrev branchingCondition (configuration : branchingConfiguration) : Prop :=
  configuration.decision (0 : Fin 3) = configuration.decision (1 : Fin 3)

def branchingInfo (agent : Fin 3) : Setoid branchingConfiguration :=
  if agent = (0 : Fin 3) then universalSetoid _
  else
    { r := fun left right =>
        left.decision (0 : Fin 3) = right.decision (0 : Fin 3) ∧
          (branchingCondition left ↔ branchingCondition right)
      iseqv :=
        ⟨fun _ => ⟨rfl, Iff.rfl⟩,
          fun h => ⟨h.1.symm, h.2.symm⟩,
          fun hleft hright =>
            ⟨hleft.1.trans hright.1, hleft.2.trans hright.2⟩⟩ }

@[simp] theorem branchingInfo_zero (left right : branchingConfiguration) :
    (branchingInfo (0 : Fin 3)).r left right := by
  show True
  trivial

@[simp] theorem branchingInfo_one (left right : branchingConfiguration) :
    (branchingInfo (1 : Fin 3)).r left right ↔
      (left.decision (0 : Fin 3) = right.decision (0 : Fin 3) ∧
        (branchingCondition left ↔ branchingCondition right)) := by
  show (_ ∧ _) ↔ _
  rfl

@[simp] theorem branchingInfo_two (left right : branchingConfiguration) :
    (branchingInfo (2 : Fin 3)).r left right ↔
      (left.decision (0 : Fin 3) = right.decision (0 : Fin 3) ∧
        (branchingCondition left ↔ branchingCondition right)) := by
  show (_ ∧ _) ↔ _
  rfl

abbrev branchingModel : Model where
  Agent := Fin 3
  Nature := Unit
  Decision := fun _ => Bool
  info := branchingInfo

/-- The later order branches on a configuration cell determined jointly by the
predecessor coordinate and another coordinate.  This is deliberately hostile:
predecessor agreement alone does not determine the branch. -/
def branchingOrder : branchingModel.Schedule 3 where
  orderAt configuration :=
    if branchingCondition configuration then
      Equiv.swap (1 : Fin 3) 2
    else Equiv.refl _

theorem branchingOrder_one_of (configuration : branchingModel.Configuration)
    (hbranch : branchingCondition configuration) :
    branchingOrder.orderAt configuration 1 = (2 : Fin 3) := by
  show (if branchingCondition configuration then Equiv.swap 1 2
    else Equiv.refl (Fin 3)) 1 = 2
  rw [if_pos hbranch]
  exact Equiv.swap_apply_left 1 2

theorem branchingOrder_one_of_not
    (configuration : branchingModel.Configuration)
    (hbranch : ¬ branchingCondition configuration) :
    branchingOrder.orderAt configuration 1 = (1 : Fin 3) := by
  show (if branchingCondition configuration then Equiv.swap 1 2
    else Equiv.refl (Fin 3)) 1 = 1
  rw [if_neg hbranch]
  rfl

theorem branchingOrder_two_of (configuration : branchingModel.Configuration)
    (hbranch : branchingCondition configuration) :
    branchingOrder.orderAt configuration 2 = (1 : Fin 3) := by
  show (if branchingCondition configuration then Equiv.swap 1 2
    else Equiv.refl (Fin 3)) 2 = 1
  rw [if_pos hbranch]
  exact Equiv.swap_apply_right 1 2

theorem branchingOrder_two_of_not
    (configuration : branchingModel.Configuration)
    (hbranch : ¬ branchingCondition configuration) :
    branchingOrder.orderAt configuration 2 = (2 : Fin 3) := by
  show (if branchingCondition configuration then Equiv.swap 1 2
    else Equiv.refl (Fin 3)) 2 = 2
  rw [if_neg hbranch]
  rfl

theorem branchingOrder_zero (configuration : branchingModel.Configuration) :
    branchingOrder.orderAt configuration 0 = (0 : Fin 3) := by
  by_cases hbranch : branchingCondition configuration
  · show (if branchingCondition configuration then Equiv.swap 1 2
      else Equiv.refl (Fin 3)) 0 = 0
    rw [if_pos hbranch]
    exact Equiv.swap_apply_of_ne_of_ne (a := (1 : Fin 3)) (b := 2) (x := 0)
      (by decide) (by decide)
  · show (if branchingCondition configuration then Equiv.swap 1 2
      else Equiv.refl (Fin 3)) 0 = 0
    rw [if_neg hbranch]
    rfl

def branchingAllFalse : branchingModel.Configuration :=
  ⟨(), fun _ => false⟩

def branchingOneTrue : branchingModel.Configuration :=
  ⟨(), fun agent => decide (agent = (1 : Fin 3))⟩

def branchingZeroOneTrue : branchingModel.Configuration :=
  ⟨(), fun agent => decide (agent = (0 : Fin 3) ∨ agent = (1 : Fin 3))⟩

theorem branchingOrder_nonconstant :
    branchingOrder.orderAt branchingAllFalse (1 : Fin 3) ≠
      branchingOrder.orderAt branchingOneTrue (1 : Fin 3) := by
  have hall : branchingCondition branchingAllFalse := by rfl
  have hone : ¬ branchingCondition branchingOneTrue := by decide
  rw [branchingOrder_one_of _ hall, branchingOrder_one_of_not _ hone]
  decide

/-- The hostile configurations separate the two causality premises.  The first
pair agrees on the predecessor but changes configuration cell; the second
stays in one cell while changing the predecessor. -/
theorem branchingPremises_independent :
    (Model.AgreeBefore branchingOrder (1 : Fin 3)
        branchingAllFalse branchingOneTrue ∧
      ¬ Model.SamePrefixThrough branchingOrder (1 : Fin 3)
        branchingAllFalse branchingOneTrue) ∧
    (Model.SamePrefixThrough branchingOrder (1 : Fin 3)
        branchingAllFalse branchingZeroOneTrue ∧
      ¬ Model.AgreeBefore branchingOrder (1 : Fin 3)
        branchingAllFalse branchingZeroOneTrue) := by
  constructor
  · constructor
    · constructor
      · rfl
      · intro earlier hearlier
        have heq : earlier = (0 : Fin 3) := Fin.ext (by omega)
        subst earlier
        rw [branchingOrder_zero]
        simp [branchingAllFalse, branchingOneTrue]
    · intro hprefix
      exact branchingOrder_nonconstant (hprefix (1 : Fin 3) (by omega))
  · constructor
    · intro earlier _
      have hall : branchingCondition branchingAllFalse := by rfl
      have hboth : branchingCondition branchingZeroOneTrue := by decide
      show (if branchingCondition branchingAllFalse then Equiv.swap 1 2
        else Equiv.refl (Fin 3)) earlier =
        (if branchingCondition branchingZeroOneTrue then Equiv.swap 1 2
        else Equiv.refl (Fin 3)) earlier
      rw [if_pos hall, if_pos hboth]
    · intro hagree
      have hzero := hagree.2 (0 : Fin 3) (by omega)
      rw [branchingOrder_zero] at hzero
      simp [branchingAllFalse, branchingZeroOneTrue] at hzero

/-- The nonconstant order is causal.  Predecessor agreement supplies the exact
agent-zero decision, while configuration-prefix agreement independently
supplies equality of the branch condition. -/
theorem branchingModel_isCausal :
    Model.IsCausalWith branchingOrder := by
  intro left right slot hprefix hagree
  have hslot : slot = 0 ∨ slot = 1 ∨ slot = 2 := by omega
  rcases hslot with rfl | rfl | rfl
  · show branchingInfo (branchingOrder.orderAt left 0) left right
    rw [branchingOrder_zero]
    exact branchingInfo_zero left right
  · have horder := hprefix (1 : Fin 3) (by omega)
    have hzero := hagree.2 (0 : Fin 3) (by omega)
    rw [branchingOrder_zero] at hzero
    have hbranch : branchingCondition left ↔ branchingCondition right := by
      constructor
      · intro hleft
        by_contra hright
        rw [branchingOrder_one_of _ hleft,
          branchingOrder_one_of_not _ hright] at horder
        have hne : (2 : Fin 3) ≠ 1 := by decide
        exact hne horder
      · intro hright
        by_contra hleft
        rw [branchingOrder_one_of_not _ hleft,
          branchingOrder_one_of _ hright] at horder
        have hne : (1 : Fin 3) ≠ 2 := by decide
        exact hne horder
    show branchingInfo (branchingOrder.orderAt left 1) left right
    by_cases hleft : branchingCondition left
    · rw [branchingOrder_one_of _ hleft]
      exact (branchingInfo_two left right).2 ⟨hzero, hbranch⟩
    · rw [branchingOrder_one_of_not _ hleft]
      exact (branchingInfo_one left right).2 ⟨hzero, hbranch⟩
  · have horder := hprefix (2 : Fin 3) (by omega)
    have hzero := hagree.2 (0 : Fin 3) (by omega)
    rw [branchingOrder_zero] at hzero
    have hbranch : branchingCondition left ↔ branchingCondition right := by
      constructor
      · intro hleft
        by_contra hright
        rw [branchingOrder_two_of _ hleft,
          branchingOrder_two_of_not _ hright] at horder
        have hne : (1 : Fin 3) ≠ 2 := by decide
        exact hne horder
      · intro hright
        by_contra hleft
        rw [branchingOrder_two_of_not _ hleft,
          branchingOrder_two_of _ hright] at horder
        have hne : (2 : Fin 3) ≠ 1 := by decide
        exact hne horder
    show branchingInfo (branchingOrder.orderAt left 2) left right
    by_cases hleft : branchingCondition left
    · rw [branchingOrder_two_of _ hleft]
      exact (branchingInfo_one left right).2 ⟨hzero, hbranch⟩
    · rw [branchingOrder_two_of_not _ hleft]
      exact (branchingInfo_two left right).2 ⟨hzero, hbranch⟩


end GameTheory.Experimental.IntrinsicOwnership
