/-
# EXP-118: arbitrary pure-policy measures read behaviorally

The public-history carrier is countably infinite. Starting from an infinite
product policy law, we push it through a measurable transformation that forces
the choices at two distinct public histories to agree while leaving every
other coordinate untouched. This within-policy correlation is not the product
law generated by its behavioral marginals. The reverse policy-measure Kuhn
layer nevertheless supplies one conditional behavioral profile for every
finite prefix, unilateral measure replacement, and discounted payoff.
-/

import GameTheory.Experimental.PostArchitecture.StochasticInfiniteKuhn

noncomputable section

namespace GameTheory.Experimental.PostArchitecture.StochasticReverseInfiniteKuhn

open GameTheory.Math.Probability GameTheory.Protocol MeasureTheory
open GameTheory.Stochastic GameTheory.Stochastic.Game

open StochasticKuhn

local instance canonicalHistoryMeasurableSpace :
    MeasurableSpace (offPathGame.toExecution false).History := ⊤

local instance actionNonempty :
    ∀ i, Nonempty (offPathGame.Action i) :=
  fun _ => ⟨false⟩

local instance actionFintype :
    ∀ i, Fintype (offPathGame.Action i) :=
  fun _ => inferInstance

local instance choiceMeasurableSpace :
    ∀ i info, MeasurableSpace
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun _ _ => ⊤

local instance choiceDiscreteMeasurableSpace :
    ∀ i info, DiscreteMeasurableSpace
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun _ _ => ⟨fun _ => MeasurableSet.of_discrete⟩

local instance choiceFintype :
    ∀ i info, Fintype
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun i info => Fintype.ofEquiv Bool
    (offPathGame.actionChoiceEquiv false i info)

local instance choiceNonempty :
    ∀ i info, Nonempty
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun i info => Nonempty.map
    (offPathGame.actionChoiceEquiv false i info) inferInstance

local instance choiceTopologicalSpace :
    ∀ i info, TopologicalSpace
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun _ _ => ⊥

local instance choiceDiscreteTopology :
    ∀ i info, DiscreteTopology
      ((offPathGame.perfectMonitoring false).Choice i info) :=
  fun _ _ => discreteTopology_bot _

/-- A noninitial public-history coordinate. -/
def laterInfo : offPathGame.PublicHistory :=
  [⟨false, fun _ => false, false⟩]

/-- Independent fair choices at every public history, used only as the source
of the hostile correlated pushforward. -/
def fairProtocolBehavioral :
    (offPathGame.perfectMonitoring false).BehavioralPolicy () :=
  fun _ => FinDist.uniformOfFintype

/-- Force the choice at `laterInfo` to equal the initial choice while leaving
all other infinitely many policy coordinates intact. -/
def correlateFirstTwo
    (policy : (offPathGame.perfectMonitoring false).Policy ()) :
    (offPathGame.perfectMonitoring false).Policy () := by
  classical
  intro info
  by_cases hinfo : info = laterInfo
  · subst info
    exact offPathGame.actionChoiceEquiv false () laterInfo
      ((offPathGame.actionChoiceEquiv false () []).symm (policy []))
  · exact policy info

@[simp]
theorem correlateFirstTwo_later
    (policy : (offPathGame.perfectMonitoring false).Policy ()) :
    correlateFirstTwo policy laterInfo =
      offPathGame.actionChoiceEquiv false () laterInfo
        ((offPathGame.actionChoiceEquiv false () []).symm (policy [])) := by
  simp [correlateFirstTwo]

theorem correlateFirstTwo_of_ne
    (policy : (offPathGame.perfectMonitoring false).Policy ())
    {info : offPathGame.PublicHistory} (hinfo : info ≠ laterInfo) :
    correlateFirstTwo policy info = policy info := by
  simp [correlateFirstTwo, hinfo]

theorem correlateFirstTwo_measurable : Measurable correlateFirstTwo := by
  rw [measurable_pi_iff]
  intro info
  by_cases hinfo : info = laterInfo
  · subst info
    simp_rw [correlateFirstTwo_later]
    exact (measurable_of_finite fun choice =>
      offPathGame.actionChoiceEquiv false () laterInfo
        ((offPathGame.actionChoiceEquiv false () []).symm choice)).comp
      (measurable_pi_apply [])
  · simp_rw [correlateFirstTwo_of_ne _ hinfo]
    exact measurable_pi_apply info

/-- The pushed-forward law has genuine within-policy correlation and retains
all untouched coordinates of the infinite source product. -/
def correlatedPolicyMeasure :
    offPathGame.ProtocolPolicyMeasure false () :=
  fairProtocolBehavioral.toPureMeasure.map correlateFirstTwo

local instance fairProtocolBehavioral_isProbability :
    IsProbabilityMeasure fairProtocolBehavioral.toPureMeasure :=
  InformationModel.BehavioralPolicy.toPureMeasure_isProbability
    (M := offPathGame.perfectMonitoring false) fairProtocolBehavioral

local instance correlatedPolicyMeasure_isProbability :
    IsProbabilityMeasure correlatedPolicyMeasure :=
  Measure.isProbabilityMeasure_map correlateFirstTwo_measurable.aemeasurable

/-- The transformation really enforces the advertised correlation. -/
theorem correlateFirstTwo_agree
    (policy : (offPathGame.perfectMonitoring false).Policy ()) :
    (correlateFirstTwo policy laterInfo).1 =
      (correlateFirstTwo policy []).1 := by
  rw [correlateFirstTwo_later,
    correlateFirstTwo_of_ne policy (by decide)]
  show some ((offPathGame.actionChoiceEquiv false () []).symm
      (policy [])) = (policy []).1
  exact congrArg Subtype.val
    ((offPathGame.actionChoiceEquiv false () []).apply_symm_apply
      (policy []))

def correlatedLaws : offPathGame.ProtocolPolicyMeasureProfile false :=
  fun _ => correlatedPolicyMeasure

local instance correlatedLaws_isProbability :
    ∀ i, IsProbabilityMeasure (correlatedLaws i) :=
  fun _ => correlatedPolicyMeasure_isProbability

def falseFallback : offPathGame.PurePublicProfile :=
  fun _ _ => false

/-- One behavioral conditional reading reproduces every finite prefix of the
correlated law. -/
theorem all_prefixes_consumer :
    ∀ horizon,
      offPathGame.protocolPolicyMeasureRun false correlatedLaws horizon =
        ((offPathGame.publicHorizonForm false horizon).play
          (offPathGame.policyMeasuresToPublicBehavioralWith false
            correlatedLaws falseFallback)).toMeasure :=
  offPathGame.kuhn_arbitraryPolicyMeasure_allFinitePrefixes false
    correlatedLaws falseFallback

/-- Replacing the sole player's measure also consumes the exact unilateral
reverse theorem on the infinite history carrier. -/
theorem unilateral_all_prefixes_consumer :
    ∀ horizon,
      offPathGame.protocolPolicyMeasureRun false
          (Profile.update
            (sig := (offPathGame.perfectMonitoring false).policyMeasureSignature)
            correlatedLaws () correlatedPolicyMeasure) horizon =
        ((offPathGame.publicHorizonForm false horizon).play
          (Profile.update
            (offPathGame.policyMeasuresToPublicBehavioralWith false
              correlatedLaws falseFallback) ()
            (offPathGame.ofBehavioralPolicy false
              (InformationModel.PolicyMeasure.toBehavioralWith
                (M := offPathGame.perfectMonitoring false)
                correlatedPolicyMeasure
                ((offPathGame.purePolicyEquiv false ()).symm
                  (falseFallback ())))))).toMeasure :=
  offPathGame.kuhn_arbitraryPolicyMeasure_update_allFinitePrefixes false
    correlatedLaws falseFallback () correlatedPolicyMeasure (falseFallback ())

theorem stageUtility_abs_le_one (state : Bool)
    (actions : ∀ _ : Unit, Bool) :
    |offPathGame.stageUtility state actions ()| ≤ 1 := by
  rw [show offPathGame.stageUtility state actions () =
      (if actions () then 1 else 0) by rfl]
  split <;> norm_num

/-- The reverse construction reaches the discounted consequence for a
nonconstant stage utility. -/
theorem discounted_consumer :
    Summable (fun time => (2 : ℝ)⁻¹ ^ time *
        offPathGame.arbitraryPolicyMeasureStageExpectation false
          correlatedLaws () time) ∧
      offPathGame.arbitraryPolicyMeasureDiscountedPayoff false (2 : ℝ)⁻¹
          correlatedLaws () =
        offPathGame.behavioralDiscountedPayoff false (2 : ℝ)⁻¹
          (offPathGame.policyMeasuresToPublicBehavioralWith false
            correlatedLaws falseFallback) () := by
  apply offPathGame.kuhn_arbitraryPolicyMeasure_discountedPayoff
    false (discount := (2 : ℝ)⁻¹) (bound := 1)
      (laws := correlatedLaws) (fallback := falseFallback) (who := ())
  · norm_num
  · norm_num
  · exact stageUtility_abs_le_one

end GameTheory.Experimental.PostArchitecture.StochasticReverseInfiniteKuhn
