/-
# Finite public monitoring

A public monitoring structure assigns a finite-support public signal law to
each chosen stage profile. Monitored strategies may depend on the complete
finite public signal history. This module constructs only finite-horizon laws;
it introduces no probability measure on infinite paths.

The central theorem gives the two equivalent recursions for a successor
history: append the newest signal to a generated prefix, or sample the first
signal and generate the rest under the corresponding continuation profile.

This native recursion is the semantic surface for repeated public-monitoring
payoffs and equilibria; it is not claimed to be a Protocol runner.  Consumers
that need a finite execution/information compiler use
`Languages.MultiRound.MonitoringGame`, whose policies also remember a player's
own earlier actions and therefore have a deliberately richer information type.
-/

import GameTheory.Repeated.Basic

noncomputable section

namespace GameTheory

open GameTheory.Math.Probability

universe uι us uo uy

variable {ι : Type uι}

namespace UtilityGame

/-- A finite-support public signal law conditional on the chosen stage
profile. -/
structure PublicMonitoring (G : UtilityGame.{uι, us, uo} ι) where
  /-- Public signal observed by every player after a stage. -/
  Signal : Type uy
  /-- Conditional law of the next public signal. -/
  signalLaw : Profile G.form.sig → FinDist Signal

namespace PublicMonitoring

variable {G : UtilityGame.{uι, us, uo} ι}

/-- A public signal history of length `t`. -/
abbrev SignalHistory (M : G.PublicMonitoring) (t : ℕ) : Type uy :=
  Fin t → M.Signal

/-- A strategy depending only on finite public signal histories. -/
abbrev MonitoredStrategy (M : G.PublicMonitoring) (i : ι) : Type _ :=
  (t : ℕ) → M.SignalHistory t → G.form.sig.Strategy i

/-- A profile of public-signal-history-dependent strategies. -/
abbrev MonitoredProfile (M : G.PublicMonitoring) : Type _ :=
  (i : ι) → M.MonitoredStrategy i

/-- Continue a monitored profile after one newly observed public signal.
`Fin.cons` keeps the successor index definitionally aligned. -/
def afterSignal (M : G.PublicMonitoring) (profile : M.MonitoredProfile)
    (signal : M.Signal) : M.MonitoredProfile :=
  fun i n history => profile i (n + 1) (Fin.cons signal history)

@[simp]
theorem afterSignal_apply (M : G.PublicMonitoring)
    (profile : M.MonitoredProfile) (signal : M.Signal) (i : ι)
    (n : ℕ) (history : M.SignalHistory n) :
    M.afterSignal profile signal i n history =
      profile i (n + 1) (Fin.cons signal history) :=
  rfl

/-- Law of the public signal history generated through a finite horizon.
The successor rule appends the newly sampled signal to the realized prefix. -/
def signalHistoryLaw (M : G.PublicMonitoring)
    (profile : M.MonitoredProfile) :
    (t : ℕ) → FinDist (M.SignalHistory t)
  | 0 => FinDist.pure fun k => k.elim0
  | t + 1 => (M.signalHistoryLaw profile t).bind fun history =>
      (M.signalLaw fun i => profile i t history).map (Fin.snoc history)

@[simp]
theorem signalHistoryLaw_zero (M : G.PublicMonitoring)
    (profile : M.MonitoredProfile) :
    M.signalHistoryLaw profile 0 = FinDist.pure (fun k => k.elim0) :=
  rfl

@[simp]
theorem signalHistoryLaw_succ (M : G.PublicMonitoring)
    (profile : M.MonitoredProfile) (t : ℕ) :
    M.signalHistoryLaw profile (t + 1) =
      (M.signalHistoryLaw profile t).bind fun history =>
        (M.signalLaw fun i => profile i t history).map
          (Fin.snoc history) :=
  rfl

/-- **Bind-first signal-prefix recursion.** A nonempty public history can be
generated by sampling the first signal and then generating the remaining
history under the corresponding continuation profile. -/
theorem signalHistoryLaw_succ_eq_bind_first
    (M : G.PublicMonitoring) (profile : M.MonitoredProfile) :
    ∀ n : ℕ,
      M.signalHistoryLaw profile (n + 1) =
        (M.signalLaw fun i => profile i 0 (fun k => k.elim0)).bind
          fun signal =>
            (M.signalHistoryLaw (M.afterSignal profile signal) n).map
              (Fin.cons (α := fun _ => M.Signal) signal)
  | 0 => by
      rw [signalHistoryLaw_succ, signalHistoryLaw_zero]
      simp only [FinDist.pure_bind, signalHistoryLaw_zero,
        FinDist.map_eq_bind]
      apply congrArg
      funext signal
      apply congrArg FinDist.pure
      funext j
      refine Fin.cases ?_ (fun k => Fin.elim0 k) j
      rfl
  | n + 1 => by
      rw [signalHistoryLaw_succ,
        signalHistoryLaw_succ_eq_bind_first M profile n]
      rw [FinDist.bind_bind]
      congr 1
      funext signal
      rw [FinDist.bind_map, signalHistoryLaw_succ, FinDist.map_bind]
      congr 1
      funext history
      show
        (M.signalLaw
            (fun i => profile i (n + 1) (Fin.cons signal history))).map
            (Fin.snoc (Fin.cons signal history)) =
          ((M.signalLaw
              (fun i => profile i (n + 1) (Fin.cons signal history))).map
              (Fin.snoc history)).map
            (Fin.cons (α := fun _ => M.Signal) signal)
      rw [FinDist.map_comp]
      congr 1
      funext next
      exact (Fin.cons_snoc_eq_snoc_cons signal history next).symm

end PublicMonitoring

end UtilityGame

end GameTheory
