/-
# Finite repeated play through Protocol

The infinite repeated path in `Basic` is deterministic semantic recursion. This
module proves that every finite prefix is the state shadow of the accepted
history runner. The protocol state is exactly the publicly observed prefix, so
its information model hides nothing and adds no second transition semantics.
-/

import GameTheory.Repeated.Basic
import GameTheory.Protocol.Strategic

noncomputable section

namespace GameTheory.Repeated

open GameTheory GameTheory.Protocol GameTheory.Math.Probability
open ExecutionProtocol

universe uι

variable {ι : Type uι}

/-- A public finite prefix of chosen stage profiles, in chronological order. -/
abbrev Prefix (G : UtilityGame ι) :=
  G.ProfileHistory

namespace Prefix

variable {G : UtilityGame ι}

/-- The empty prefix. -/
def empty (G : UtilityGame ι) : Prefix G :=
  []

/-- Append one chosen stage profile. -/
def snoc (state : Prefix G) (profile : Profile G.form.sig) : Prefix G :=
  state.concat profile

/-- The prefix generated by an infinite repeated profile. -/
def ofPlay (G : UtilityGame ι) (profile : G.RepeatedProfile)
    (rounds : ℕ) : Prefix G :=
  List.ofFn fun t : Fin rounds => G.repeatedPlay profile t

/-- Appending period `t` to its generated prefix gives the generated prefix of
length `t + 1`. -/
theorem snoc_ofPlay (G : UtilityGame ι) (profile : G.RepeatedProfile)
    (t : ℕ) :
    (ofPlay G profile t).snoc (G.repeatedPlay profile t) =
      ofPlay G profile (t + 1) := by
  simpa [snoc, ofPlay] using
    (List.ofFn_succ'
      (fun k : Fin (t + 1) => G.repeatedPlay profile k)).symm

@[simp]
theorem length_ofPlay (G : UtilityGame ι) (profile : G.RepeatedProfile)
    (t : ℕ) :
    (ofPlay G profile t).length = t := by
  unfold ofPlay
  exact List.length_ofFn

/-- Recover the action profile from a legal all-active joint contribution. -/
private def actionOfJoint (joint : ∀ i, Option (G.form.sig.Strategy i))
    (active : Prop)
    (hlegal : IsLegalJoint (fun _ => active) (fun _ => Set.univ) joint)
    (hactive : active) : Profile G.form.sig :=
  fun i =>
    match h : joint i with
    | some action => action
    | none => False.elim (by
        have hi := hlegal i
        rw [h] at hi
        exact hi hactive)

@[simp]
private theorem actionOfJoint_some (actions : Profile G.form.sig)
    (active : Prop)
    (hlegal : IsLegalJoint (fun _ => active) (fun _ => Set.univ)
      (fun i => some (actions i)))
    (hactive : active) :
    actionOfJoint (fun i => some (actions i)) active hlegal hactive =
      actions := by
  funext i
  rfl

end Prefix

/-- Execute exactly `horizon` stages of public-action repeated play. -/
@[reducible]
def execution (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] : ExecutionProtocol ι where
  State := Prefix G
  Action := G.form.sig.Strategy
  init := Prefix.empty G
  active state _ := state.length < horizon
  available _ _ := Set.univ
  terminal state := horizon ≤ state.length
  step state joint :=
    let hactive : state.length < horizon :=
      Nat.lt_of_not_ge joint.2.1
    FinDist.pure (state.snoc
      (Prefix.actionOfJoint joint.1 (state.length < horizon)
        joint.2.2 hactive))
  progress := by
    intro state hterm
    have hactive : state.length < horizon := Nat.lt_of_not_ge hterm
    refine ⟨fun i => some
      (Classical.choice (inferInstance :
        Nonempty (G.form.sig.Strategy i))), fun i => ?_⟩
    exact ⟨hactive, Set.mem_univ _⟩

/-- Signals reveal exactly the public prefix reached by a transition. -/
@[reducible]
def signals (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] :
    InfoSignals (execution G horizon) where
  PublicSignal := Prefix G
  PrivateSignal _ := Unit
  initialPublic := Prefix.empty G
  initialPrivate _ := ()
  publicSignal event := event.target
  privateSignal _ _ := ()
  InfoState _ := Prefix G
  initInfo _ _ publicPrefix := publicPrefix
  pushInfo _ _ _ _ publicPrefix := publicPrefix

/-- Because the whole prefix is public, every player's local information state
is exactly the execution state reached. -/
theorem infoOf_eq_state (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] (i : ι)
    {state : (execution G horizon).State}
    (trace : Trace (execution G horizon) state) :
    (signals G horizon).infoOf i trace = state := by
  cases trace with
  | start => rfl
  | extend prior joint isLegal realized =>
      rw [InfoSignals.infoOf_extend]

/-- The public-prefix menu asks every player to act until the horizon, and
forces the protocol no-op afterwards. -/
def menu (G : UtilityGame ι) (horizon : ℕ) (i : ι) :
    Prefix G → Set (Option (G.form.sig.Strategy i))
  | state =>
      if state.length < horizon then
        { choice | ∃ action, choice = some action }
      else
        {none}

/-- The public-prefix menu agrees with execution legality after every history. -/
theorem menu_adequate (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] (i : ι)
    {state : (execution G horizon).State}
    (trace : Trace (execution G horizon) state)
    (choice : Option (G.form.sig.Strategy i)) :
    choice ∈ menu G horizon i ((signals G horizon).infoOf i trace) ↔
      LegalOption (execution G horizon) state i choice := by
  rw [infoOf_eq_state G horizon i trace]
  by_cases hactive : state.length < horizon <;>
    cases choice <;>
    simp [menu, LegalOption, execution, hactive]

/-- Perfect public monitoring for a finite repeated prefix. -/
@[reducible]
def informationModel (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] :
    InformationModel (execution G horizon) where
  toInfoSignals := signals G horizon
  menu := menu G horizon
  menu_adequate := by
    intro i _ trace choice
    exact menu_adequate G horizon i trace choice

namespace Policy

variable {G : UtilityGame ι} {horizon : ℕ}
  [∀ i, Nonempty (G.form.sig.Strategy i)]

/-- Restrict an infinite repeated strategy to the finite-prefix information
model. Choices after the horizon are forced no-ops. -/
def ofRepeated {i : ι} (strategy : G.RepeatedStrategy i) :
    (informationModel G horizon).Policy i :=
  fun state =>
    if hactive : state.length < horizon then
      ⟨some (strategy state), by
        simp [menu, hactive]⟩
    else
      ⟨none, by simp [menu, hactive]⟩

end Policy

/-- Restrict a repeated profile coordinatewise to finite-prefix policies. -/
def policyProfileOfRepeated (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) :
    Profile (informationModel G horizon).strategicSignature :=
  fun i => Policy.ofRepeated (profile i)

/-- State-indexed chooser induced by a repeated profile. -/
def chooserOfRepeated (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) : (execution G horizon).Chooser :=
  fun state hterm =>
    have hactive : state.length < horizon := Nat.lt_of_not_ge hterm
    ⟨fun i => some (profile i state), hterm,
      fun _ => ⟨hactive, Set.mem_univ _⟩⟩

/-- Restricted policies drive the same chooser as the repeated profile. -/
theorem historyChooser_policyProfileOfRepeated (G : UtilityGame ι)
    (horizon : ℕ) [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) :
    (informationModel G horizon).historyChooser
        (policyProfileOfRepeated G horizon profile) =
      (chooserOfRepeated G horizon profile).toHistoryChooser := by
  apply funext
  rintro ⟨state, trace⟩
  apply funext
  intro hterm
  apply Subtype.ext
  funext i
  show (policyProfileOfRepeated G horizon profile i).act
      ((informationModel G horizon).infoOf i trace) =
    (chooserOfRepeated G horizon profile state hterm).1 i
  have hinfo : (informationModel G horizon).infoOf i trace = state :=
    infoOf_eq_state G horizon i trace
  rw [hinfo]
  have hactive : state.length < horizon := Nat.lt_of_not_ge hterm
  simp [policyProfileOfRepeated, Policy.ofRepeated, hactive,
    chooserOfRepeated, InformationModel.Policy.act]

/-- One protocol step from a generated prefix appends the next generated stage
profile. -/
theorem step_chooserOfRepeated_ofPlay (G : UtilityGame ι)
    (horizon : ℕ) [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) {t : ℕ} (ht : t < horizon) :
    (execution G horizon).step (Prefix.ofPlay G profile t)
        (chooserOfRepeated G horizon profile (Prefix.ofPlay G profile t)
          (by simpa [execution, Prefix.ofPlay] using ht)) =
      FinDist.pure (Prefix.ofPlay G profile (t + 1)) := by
  have hactions :
      (fun i => profile i (Prefix.ofPlay G profile t)) =
        G.repeatedPlay profile t := by
    funext i
    rw [UtilityGame.repeatedPlay]
    rfl
  apply congrArg FinDist.pure
  show (Prefix.ofPlay G profile t).snoc
      (fun i => profile i (Prefix.ofPlay G profile t)) = _
  rw [hactions]
  exact Prefix.snoc_ofPlay G profile t

/-- Running from a generated prefix to the fixed horizon returns exactly the
corresponding longer generated prefix. -/
theorem runFor_chooserOfRepeated_to_horizon (G : UtilityGame ι)
    (horizon : ℕ) [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) :
    ∀ {fuel t : ℕ}, t + fuel = horizon →
      (execution G horizon).runFor (chooserOfRepeated G horizon profile)
          fuel (Prefix.ofPlay G profile t) =
        FinDist.pure (Prefix.ofPlay G profile horizon) := by
  intro fuel
  induction fuel with
  | zero =>
      intro t ht
      simp at ht
      subst ht
      rfl
  | succ fuel ih =>
      intro t ht
      have hactive : t < horizon := by omega
      have hterm :
          ¬(execution G horizon).terminal (Prefix.ofPlay G profile t) := by
        simpa [execution, Prefix.ofPlay] using hactive
      rw [ExecutionProtocol.runFor_succ_of_not_terminal
        (chooserOfRepeated G horizon profile) fuel hterm]
      rw [step_chooserOfRepeated_ofPlay G horizon profile hactive,
        FinDist.pure_bind]
      exact ih (by omega)

/-- The finite-prefix protocol form, with the reached public prefix as outcome. -/
@[reducible]
def toProtocolForm (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)] : GameForm ι :=
  ((informationModel G horizon).toGameForm horizon).mapOutcome
    ExecutionProtocol.History.state

/-- **Finite-prefix compiler law.** Running the restricted policies for the
horizon produces exactly the prefix of the native repeated path. -/
theorem toProtocolForm_play_policyProfileOfRepeated
    (G : UtilityGame ι) (horizon : ℕ)
    [∀ i, Nonempty (G.form.sig.Strategy i)]
    (profile : G.RepeatedProfile) :
    (toProtocolForm G horizon).play
        (policyProfileOfRepeated G horizon profile) =
      FinDist.pure (Prefix.ofPlay G profile horizon) := by
  have hshadow := map_state_runHistoryFor
    (chooserOfRepeated G horizon profile) horizon
    (execution G horizon).initHistory
  rw [← historyChooser_policyProfileOfRepeated G horizon profile] at hshadow
  show FinDist.map ExecutionProtocol.History.state
      ((informationModel G horizon).run
        (policyProfileOfRepeated G horizon profile) horizon) =
    FinDist.pure (Prefix.ofPlay G profile horizon)
  rw [InformationModel.run, InformationModel.runFrom]
  calc
    FinDist.map ExecutionProtocol.History.state
        ((execution G horizon).runHistoryFor
          ((informationModel G horizon).historyChooser
            (policyProfileOfRepeated G horizon profile))
          horizon (execution G horizon).initHistory) =
      (execution G horizon).runFor
        (chooserOfRepeated G horizon profile) horizon
        (execution G horizon).initHistory.state := hshadow
    _ = FinDist.pure (Prefix.ofPlay G profile horizon) := by
      simpa [execution, Prefix.empty, Prefix.ofPlay] using
        runFor_chooserOfRepeated_to_horizon G horizon profile
          (fuel := horizon) (t := 0) (by omega)

end GameTheory.Repeated
