/-
# Finite-support principal-agent contracts

Hidden-action moral-hazard environments with risk-neutral agents,
finite-support outcome laws, outcome-contingent payments, and explicit outside
options.
-/

import GameTheory.Math.Probability.FinDist

noncomputable section

namespace GameTheory.Mechanism

open GameTheory.Math.Probability

universe uAction uOutcome

/-- A hidden-action principal-agent environment. Each action induces a
finite-support outcome law, while rewards and effort costs are real-valued. -/
structure PrincipalAgent (Action : Type uAction) (Outcome : Type uOutcome) where
  /-- The outcome law each hidden action induces. -/
  outcomeLaw : Action → FinDist Outcome
  /-- What the principal earns at each outcome. -/
  reward : Outcome → ℝ
  /-- The effort cost the agent bears for each action. -/
  cost : Action → ℝ

namespace PrincipalAgent

variable {Action : Type uAction} {Outcome : Type uOutcome}

/-- An outcome-contingent payment is limited-liability when it never charges the
agent. This predicate is independent of a particular environment. -/
def IsLimitedLiability (payment : Outcome → ℝ) : Prop :=
  ∀ outcome, 0 ≤ payment outcome

variable (I : PrincipalAgent Action Outcome)

/-- Expected payment received by the agent from an action. -/
def expectedPayment (payment : Outcome → ℝ) (action : Action) : ℝ :=
  (I.outcomeLaw action).expect payment

/-- Agent payoff: expected payment less private effort cost. -/
def agentUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  I.expectedPayment payment action - I.cost action

/-- Principal payoff: expected realized reward net of payment. -/
def principalUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  (I.outcomeLaw action).expect fun outcome => I.reward outcome - payment outcome

/-- Expected gross reward from an action. -/
def expectedReward (action : Action) : ℝ :=
  (I.outcomeLaw action).expect I.reward

/-- Total expected surplus generated by an action. -/
def socialSurplus (action : Action) : ℝ :=
  I.expectedReward action - I.cost action

/-- Linear commission contract: a fixed share of realized reward. -/
def linearPayment (α : ℝ) : Outcome → ℝ := fun outcome => α * I.reward outcome

/-- An action is incentive compatible when it maximizes the agent's payoff. -/
def IsIncentivized (payment : Outcome → ℝ) (action : Action) : Prop :=
  ∀ alternative, I.agentUtility payment alternative ≤ I.agentUtility payment action

/-- The agent accepts an action when it meets the stated outside option. -/
def Participates (outsideOption : ℝ) (payment : Outcome → ℝ) (action : Action) : Prop :=
  outsideOption ≤ I.agentUtility payment action

/-- A contract offers participation when some available action meets the outside
option. -/
def OffersParticipation (outsideOption : ℝ) (payment : Outcome → ℝ) : Prop :=
  ∃ action, I.Participates outsideOption payment action

theorem principalUtility_add_agentUtility (payment : Outcome → ℝ) (action : Action) :
    I.principalUtility payment action + I.agentUtility payment action =
      I.socialSurplus action := by
  unfold principalUtility agentUtility expectedPayment socialSurplus expectedReward
  rw [show (fun outcome => I.reward outcome - payment outcome) =
      (fun outcome => I.reward outcome + (-1 : ℝ) * payment outcome) by
        funext outcome; ring,
    FinDist.expect_add, FinDist.expect_smul]
  ring

theorem agentUtility_ge (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    (action : Action) : -I.cost action ≤ I.agentUtility payment action := by
  have hnonneg : 0 ≤ I.expectedPayment payment action := by
    rw [← FinDist.expect_const (I.outcomeLaw action) 0]
    exact FinDist.expect_mono fun outcome _ => hpayment outcome
  unfold agentUtility
  linarith

theorem linearPayment_limitedLiability {α : ℝ} (hα : 0 ≤ α)
    (hreward : ∀ outcome, 0 ≤ I.reward outcome) :
    IsLimitedLiability (I.linearPayment α) :=
  fun outcome => mul_nonneg hα (hreward outcome)

theorem agentUtility_linearPayment (α : ℝ) (action : Action) :
    I.agentUtility (I.linearPayment α) action =
      α * I.expectedReward action - I.cost action := by
  unfold agentUtility expectedPayment linearPayment expectedReward
  rw [FinDist.expect_smul]

theorem principalUtility_linearPayment (α : ℝ) (action : Action) :
    I.principalUtility (I.linearPayment α) action =
      (1 - α) * I.expectedReward action := by
  unfold principalUtility linearPayment expectedReward
  rw [show (fun outcome => I.reward outcome - α * I.reward outcome) =
      (fun outcome => (1 - α) * I.reward outcome) by
        funext outcome; ring,
    FinDist.expect_smul]

theorem agentUtility_linearPayment_one (action : Action) :
    I.agentUtility (I.linearPayment 1) action = I.socialSurplus action := by
  rw [agentUtility_linearPayment]
  simp [socialSurplus]

theorem principalUtility_linearPayment_one (action : Action) :
    I.principalUtility (I.linearPayment 1) action = 0 := by
  rw [principalUtility_linearPayment]
  ring

theorem exists_incentivized [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) : ∃ action, I.IsIncentivized payment action := by
  obtain ⟨action, haction⟩ := Finite.exists_max (I.agentUtility payment)
  exact ⟨action, haction⟩

theorem isIncentivized_linearPayment_one_iff (action : Action) :
    I.IsIncentivized (I.linearPayment 1) action ↔
      ∀ alternative, I.socialSurplus alternative ≤ I.socialSurplus action := by
  simp only [IsIncentivized, agentUtility_linearPayment_one]

theorem agentUtility_mono (payment payment' : Outcome → ℝ)
    (hpayment : ∀ outcome, payment outcome ≤ payment' outcome) (action : Action) :
    I.agentUtility payment action ≤ I.agentUtility payment' action := by
  have h := FinDist.expect_mono (μ := I.outcomeLaw action)
    (fun outcome _ => hpayment outcome)
  unfold agentUtility expectedPayment
  linarith

theorem participates_of_offersParticipation_of_isIncentivized
    {outsideOption : ℝ} {payment : Outcome → ℝ} {action : Action}
    (hoffers : I.OffersParticipation outsideOption payment)
    (hincentive : I.IsIncentivized payment action) :
    I.Participates outsideOption payment action := by
  obtain ⟨alternative, hparticipates⟩ := hoffers
  exact le_trans hparticipates (hincentive alternative)

theorem offersParticipation_zero_of_costless_of_limitedLiability
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0) :
    I.OffersParticipation 0 payment := by
  refine ⟨costless, ?_⟩
  have h := I.agentUtility_ge payment hpayment costless
  simpa [Participates, hcostless] using h

theorem participates_zero_of_costless_of_limitedLiability_of_isIncentivized
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0) {action : Action}
    (hincentive : I.IsIncentivized payment action) :
    I.Participates 0 payment action :=
  I.participates_of_offersParticipation_of_isIncentivized
    (I.offersParticipation_zero_of_costless_of_limitedLiability payment hpayment hcostless)
    hincentive

theorem principalUtility_le_socialSurplus_sub_outsideOption
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hparticipates : I.Participates outsideOption payment action) :
    I.principalUtility payment action ≤ I.socialSurplus action - outsideOption := by
  have h := I.principalUtility_add_agentUtility payment action
  have houtside : outsideOption ≤ I.agentUtility payment action := hparticipates
  linarith

theorem principalUtility_le_socialSurplus_of_participates_zero
    (payment : Outcome → ℝ) {action : Action}
    (hparticipates : I.Participates 0 payment action) :
    I.principalUtility payment action ≤ I.socialSurplus action := by
  simpa using I.principalUtility_le_socialSurplus_sub_outsideOption payment hparticipates

theorem principalUtility_eq_socialSurplus_sub_outsideOption_iff
    (payment : Outcome → ℝ) (outsideOption : ℝ) (action : Action) :
    I.principalUtility payment action = I.socialSurplus action - outsideOption ↔
      I.agentUtility payment action = outsideOption := by
  have h := I.principalUtility_add_agentUtility payment action
  constructor <;> intro he <;> linarith

theorem principalUtility_eq_socialSurplus_iff
    (payment : Outcome → ℝ) (action : Action) :
    I.principalUtility payment action = I.socialSurplus action ↔
      I.agentUtility payment action = 0 := by
  simpa using I.principalUtility_eq_socialSurplus_sub_outsideOption_iff payment 0 action

theorem principalUtility_le_firstBest [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hparticipates : I.Participates outsideOption payment action) :
    ∃ best : Action, (∀ alternative, I.socialSurplus alternative ≤ I.socialSurplus best) ∧
      I.principalUtility payment action ≤ I.socialSurplus best - outsideOption := by
  obtain ⟨best, hbest⟩ := Finite.exists_max I.socialSurplus
  refine ⟨best, hbest, ?_⟩
  exact le_trans (I.principalUtility_le_socialSurplus_sub_outsideOption payment hparticipates)
    (sub_le_sub_right (hbest action) outsideOption)

theorem principalUtility_le_firstBest_zero [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {action : Action}
    (hparticipates : I.Participates 0 payment action) :
    ∃ best : Action, (∀ alternative, I.socialSurplus alternative ≤ I.socialSurplus best) ∧
      I.principalUtility payment action ≤ I.socialSurplus best := by
  simpa using I.principalUtility_le_firstBest payment hparticipates

end PrincipalAgent

end GameTheory.Mechanism
