/-
# Intrinsic-form game syntax

This module owns the closed-loop configuration semantics of an intrinsic game:
information-local decision rules, their fixed points, and causality relative to
a configuration-dependent schedule.  It deliberately carries no finite
enumeration, probability law, player ownership, utility, compiler, or mixed
strategy layer; those belong to consumers that need them. Solvability and
causality are expressed without storing enumeration or execution capabilities
in the model.
-/

import Mathlib.Logic.Equiv.Defs

namespace GameTheory.Languages.Intrinsic

universe uAgent uNature uDecision

/-- A closed-loop configuration records nature and every agent's decision at
once.  It is not a Protocol history: no temporal order has yet been chosen. -/
structure Config (Nature : Type uNature) (Agent : Type uAgent)
    (Decision : Agent → Type uDecision) where
  /-- The state of nature. -/
  nature : Nature
  /-- Every agent's decision, taken simultaneously. -/
  decision : (agent : Agent) → Decision agent

/-- An intrinsic model provides decision agents, nature, decision carriers,
and each agent's information equivalence relation on complete configurations.
No finite or decidable-equality capability is stored in the syntax. -/
structure Model where
  /-- The decision agents. -/
  Agent : Type uAgent
  /-- The states of nature. -/
  Nature : Type uNature
  /-- Each agent's decision carrier. -/
  Decision : Agent → Type uDecision
  /-- What each agent can distinguish: configurations related here are
  indistinguishable to that agent. -/
  info : (agent : Agent) → Setoid (Config Nature Agent Decision)

-- Agents, nature, and dependent decisions intentionally have independent
-- universes; the linter sees them only through `Config` inside this record.

namespace Model

/-- The complete closed-loop configuration space of an intrinsic model. -/
abbrev Configuration (M : Model.{uAgent, uNature, uDecision}) :=
  Config M.Nature M.Agent M.Decision

/-- One agent's decision rule, constant on that agent's information classes. -/
structure PureStrategy (M : Model.{uAgent, uNature, uDecision}) (agent : M.Agent) where
  /-- The decision taken at each configuration. -/
  act : M.Configuration → M.Decision agent
  respects : ∀ left right,
    (M.info agent).r left right → act left = act right

/-- A family of information-local pure decision rules. -/
abbrev PureProfile (M : Model.{uAgent, uNature, uDecision}) :=
  (agent : M.Agent) → M.PureStrategy agent

/-- The simultaneous closed-loop equations generated by an intrinsic pure
profile at a fixed nature state. -/
def IsFixedPoint (M : Model.{uAgent, uNature, uDecision}) (profile : M.PureProfile)
    (nature : M.Nature) (decision : (agent : M.Agent) → M.Decision agent) :
    Prop :=
  ∀ agent, decision agent =
    (profile agent).act ⟨nature, decision⟩

/-- Every pure profile and nature state has a unique closed-loop solution. -/
def IsSolvable (M : Model.{uAgent, uNature, uDecision}) : Prop :=
  ∀ (profile : M.PureProfile) (nature : M.Nature),
    ∃! decision : (agent : M.Agent) → M.Decision agent,
      M.IsFixedPoint profile nature decision

/-- A configuration-dependent exhaustive order. The slot count is explicit;
no global finite-agent capability is stored in the model. -/
structure Schedule (M : Model.{uAgent, uNature, uDecision}) (slots : Nat) where
  /-- The order agents are visited in, which may itself depend on the
  configuration. -/
  orderAt : M.Configuration → Fin slots ≃ M.Agent

/-- Two configurations choose the same schedule through the current slot. -/
def SamePrefixThrough {M : Model.{uAgent, uNature, uDecision}} {slots : Nat}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) : Prop :=
  ∀ earlier : Fin slots, earlier.1 ≤ slot.1 →
    schedule.orderAt left earlier = schedule.orderAt right earlier

/-- `candidate` lies in the configuration-prefix cell of `reference` through
the first `count` scheduled agents. -/
def PrefixCell {M : Model.{uAgent, uNature, uDecision}} {slots : Nat}
    (schedule : M.Schedule slots) (reference : M.Configuration)
    (count : Nat) (candidate : M.Configuration) : Prop :=
  ∀ earlier : Fin slots, earlier.1 < count →
    schedule.orderAt candidate earlier = schedule.orderAt reference earlier

/-- Direct comparison of two schedule prefixes is exactly membership in the
configuration-prefix cell through the current slot. -/
theorem samePrefixThrough_iff_prefixCell
    {M : Model.{uAgent, uNature, uDecision}} {slots : Nat}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) :
    SamePrefixThrough schedule slot left right ↔
      PrefixCell schedule left (slot.1 + 1) right := by
  constructor
  · intro hprefix earlier hearlier
    exact (hprefix earlier (Nat.le_of_lt_succ hearlier)).symm
  · intro hcell earlier hearlier
    exact (hcell earlier (Nat.lt_succ_of_le hearlier)).symm

/-- Nature and every already-made decision agree before the current slot. -/
def AgreeBefore {M : Model.{uAgent, uNature, uDecision}} {slots : Nat}
    (schedule : M.Schedule slots) (slot : Fin slots)
    (left right : M.Configuration) : Prop :=
  left.nature = right.nature ∧
    ∀ earlier : Fin slots, earlier.1 < slot.1 →
      left.decision (schedule.orderAt left earlier) =
        right.decision (schedule.orderAt left earlier)

/-- At the current slot, information may depend on nature and predecessor
decisions, but not on a decision scheduled later. -/
def IsCausalWith {M : Model.{uAgent, uNature, uDecision}} {slots : Nat}
    (schedule : M.Schedule slots) : Prop :=
  ∀ (left right : M.Configuration) (slot : Fin slots),
    SamePrefixThrough schedule slot left right →
    AgreeBefore schedule slot left right →
    (M.info (schedule.orderAt left slot)).r left right

end Model

end GameTheory.Languages.Intrinsic
