/-
# Intrinsic selected-solution fixture

The opt-in solution leaf is exercised on a solvable two-agent intrinsic model.
The selected fixed point is nonconstant across agents, so the selector cannot
pass by returning an arbitrary constant profile.
-/

import GameTheory.Examples.Intrinsic
import GameTheory.Languages.Intrinsic.Solution

namespace GameTheory.Tests.IntrinsicSolution

open GameTheory.Examples.Intrinsic
open GameTheory.Languages.Intrinsic

/-- Each no-information agent constantly chooses its own Boolean name. -/
def identityProfile : noInformation.PureProfile :=
  fun agent =>
    { act := fun _ => agent
      respects := by
        intro _ _ _
        rfl }

/-- The selected closed-loop solution is the explicit nonconstant fixed point
generated by `identityProfile`. -/
theorem selected_solution_eq_identity :
    noInformation.solution noInformation_isSolvable identityProfile () =
      fun agent => agent := by
  funext agent
  exact Model.solution_apply noInformation noInformation_isSolvable identityProfile () agent

/-- In particular, the selector preserves the distinction between the two
decision coordinates. -/
theorem selected_solution_distinguishes_agents :
    noInformation.solution noInformation_isSolvable identityProfile () false ≠
      noInformation.solution noInformation_isSolvable identityProfile () true := by
  rw [congrFun selected_solution_eq_identity false,
    congrFun selected_solution_eq_identity true]
  exact Bool.false_ne_true

end GameTheory.Tests.IntrinsicSolution
