/-
# One simultaneous full-game CFR trace

All local regret tables read the same current behavioral profile. The next
round is computed from that snapshot; no local learner receives an unrelated
environment sequence or an assumed root-regret conclusion.
-/

import GameTheory.Analysis.ReBeL.RegretMatching
import GameTheory.Analysis.ReBeL.LocalRegret
import GameTheory.ReBeL.Schedule

noncomputable section

namespace GameTheory.ReBeL

open GameTheory.Protocol GameTheory.Protocol.InformationModel
open GameTheory.Math.Probability GameTheory.Analysis.Approachability
open GameTheory.Math.Approachability GameTheory.Math.OrthantProjection

universe uι us ua up uq uk
variable {ι : Type uι} {E : ExecutionProtocol.{uι, us, ua} ι}
variable (M : InformationModel.{uι, us, ua, up, uq, uk} E)

/-- One average-regret vector at every genuine decision information site. -/
abbrev CFRState := (who : ι) → (site : M.InformationSite who) →
  EuclideanSpace ℝ (M.Choice who site.1)

variable [∀ who info, Fintype (M.Choice who info)]

/-- A single behavioral profile is assembled from all current tables. Outside
actual decision sites the explicitly supplied legal fallback is used. -/
def cfrProfile (fallback : (who : ι) → M.Policy who) (state : CFRState M) :
    Profile M.behavioralSignature := by
  classical
  exact fun who info =>
    if h : ∃ history : M.InformationHistory who info,
        ¬ E.terminal history.1.state ∧ ∃ action, some action ∈ M.menu who info then
      regretMatchWith (fallback who info) (state who ⟨info, h⟩)
    else FinDist.pure (fallback who info)

/-- At every actual decision site the joint profile uses precisely that
site's current regret table and prescribed zero-mass fallback. -/
@[simp]
theorem cfrProfile_at_site (fallback : (who : ι) → M.Policy who) (state : CFRState M)
    (who : ι) (site : M.InformationSite who) :
    cfrProfile M fallback state who site.1 =
      regretMatchWith (fallback who site.1) (state who site) := by
  classical
  unfold cfrProfile
  rw [dif_pos site.2]
  rfl

variable [Fintype ι] [DecidableEq ι] [Fintype E.History]
variable [∀ who, DecidableEq (M.InfoState who)]

/-- Simultaneous vanilla CFR in average-regret coordinates. Round zero has
no observations. Every update uses the complete previous-round profile. -/
def cfrState (clock : ObservationClock M) (fallback : (who : ι) → M.Policy who)
    (payoff : ι → E.History → ℝ) (horizon : ℕ) : ℕ → CFRState M
  | 0 => fun _ _ => 0
  | n + 1 =>
      let previous := cfrState clock fallback payoff horizon n
      let strategy := cfrProfile M fallback previous
      fun who site =>
        ((n : ℝ) / ((n : ℝ) + 1)) • previous who site +
          (1 / ((n : ℝ) + 1)) • M.localCounterfactualRegretVector strategy who site
            (payoff who) (horizon - clock.depth who site.1)

/-- The unique simultaneous play sequence generated by all local tables. -/
def cfrPlay (clock : ObservationClock M) (fallback : (who : ι) → M.Policy who)
    (payoff : ι → E.History → ℝ) (horizon n : ℕ) : Profile M.behavioralSignature :=
  cfrProfile M fallback (cfrState M clock fallback payoff horizon n)

/-- A pointwise recurrence preserves the named information-site carrier
instead of exposing a semireducible dependent function during rewriting. -/
theorem cfrState_succ_at (clock : ObservationClock M)
    (fallback : (who : ι) → M.Policy who) (payoff : ι → E.History → ℝ)
    (horizon n : ℕ) (who : ι) (site : M.InformationSite who) :
    cfrState M clock fallback payoff horizon (n + 1) who site =
      ((n : ℝ) / ((n : ℝ) + 1)) • cfrState M clock fallback payoff horizon n who site +
        (1 / ((n : ℝ) + 1)) • M.localCounterfactualRegretVector
          (cfrPlay M clock fallback payoff horizon n) who site (payoff who)
          (horizon - clock.depth who site.1) := rfl

/-- With no completed iterations, every information-local law is the supplied
fallback. This fixes the indexing and does not silently insert a warm start. -/
theorem cfrPlay_zero (clock : ObservationClock M) (fallback : (who : ι) → M.Policy who)
    (payoff : ι → E.History → ℝ) (horizon : ℕ) :
    cfrPlay M clock fallback payoff horizon 0 = fun who => (fallback who).toBehavioral := by
  classical
  funext who info
  unfold cfrPlay cfrState cfrProfile
  split <;> simp [Policy.toBehavioral]

/-- The actual instantaneous vector at each site is the regret payoff of its
own matcher against the very same whole-game play snapshot used everywhere. -/
theorem cfr_instantaneous_realization (clock : ObservationClock M)
    (hrecall : M.PerfectRecall) (fallback : (who : ι) → M.Policy who)
    (payoff : ι → E.History → ℝ) (horizon n : ℕ)
    (who : ι) (site : M.InformationSite who) :
    M.localCounterfactualRegretVector (cfrPlay M clock fallback payoff horizon n)
        who site (payoff who) (horizon - clock.depth who site.1) =
      regretPayoff
        (fun choice strategy => M.counterfactualActionUtility strategy who site
          (payoff who) (horizon - clock.depth who site.1) choice)
        (regretMatchWith (fallback who site.1)
          (cfrState M clock fallback payoff horizon n who site))
        (cfrPlay M clock fallback payoff horizon n) := by
  rw [localVector_eq_regretPayoff M
    (M.actsOnceWhereItMatters_of_perfectRecall hrecall)]
  unfold cfrPlay
  rw [cfrProfile_at_site]
  rfl

/-- The coupled table is not a separate hypothetical local process: it equals
canonical reactive averaging along the constructed full-game environment. -/
theorem cfrState_eq_avgVec (clock : ObservationClock M) (hrecall : M.PerfectRecall)
    (fallback : (who : ι) → M.Policy who) (payoff : ι → E.History → ℝ)
    (horizon : ℕ) (who : ι) (site : M.InformationSite who) (n : ℕ) :
    cfrState M clock fallback payoff horizon n who site =
      avgVec (regretPayoff
        (fun choice strategy => M.counterfactualActionUtility strategy who site
          (payoff who) (horizon - clock.depth who site.1) choice))
        (regretMatchWith (fallback who site.1))
        (cfrPlay M clock fallback payoff horizon) n := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [cfrState_succ_at, cfr_instantaneous_realization M clock hrecall, ih]
      rfl

/-- Every table equals the sum of the actual canonical local regrets divided
by the number of completed rounds. The identity also holds at zero rounds. -/
theorem cfrState_smul_eq_sum (clock : ObservationClock M)
    (fallback : (who : ι) → M.Policy who) (payoff : ι → E.History → ℝ)
    (horizon : ℕ) (who : ι) (site : M.InformationSite who) (t : ℕ) :
    (t : ℝ) • cfrState M clock fallback payoff horizon t who site =
      ∑ n ∈ Finset.range t,
        M.localCounterfactualRegretVector (cfrPlay M clock fallback payoff horizon n)
          who site (payoff who) (horizon - clock.depth who site.1) := by
  induction t with
  | zero => simp [cfrState]
  | succ n ih =>
      have hn : (n : ℝ) + 1 ≠ 0 := by positivity
      have c1 : ((n : ℝ) + 1) * ((n : ℝ) / ((n : ℝ) + 1)) = (n : ℝ) := by
        field_simp
      have c2 : ((n : ℝ) + 1) * (1 / ((n : ℝ) + 1)) = 1 := by field_simp
      rw [Finset.sum_range_succ, ← ih, cfrState_succ_at]
      simp only [Nat.cast_add, Nat.cast_one]
      rw [smul_add, smul_smul, smul_smul, c1, c2, one_smul]

/-- Uniformly bounded canonical action values supply a finite-time bound to
the actual coupled table, not merely to a separately postulated learner. -/
theorem cfrState_sq_distance_le (clock : ObservationClock M) (hrecall : M.PerfectRecall)
    (fallback : (who : ι) → M.Policy who) (payoff : ι → E.History → ℝ)
    (horizon : ℕ) (who : ι) (site : M.InformationSite who)
    {bound : ℝ} (hbound0 : 0 ≤ bound)
    (hbound : ∀ law strategy, ‖regretPayoff
      (fun choice current => M.counterfactualActionUtility current who site
        (payoff who) (horizon - clock.depth who site.1) choice) law strategy‖ ≤ bound)
    (t : ℕ) :
    Metric.infDist (cfrState M clock fallback payoff horizon t who site)
      nonposOrthant ^ 2 * (t : ℝ) ≤ (2 * bound) ^ 2 := by
  rw [cfrState_eq_avgVec M clock hrecall]
  exact regretMatchWith_sq_infDist_avg_le (fallback who site.1) _ hbound0 hbound _ t

end GameTheory.ReBeL
