/-
# Actual event-selection controls

A live canonical solver is run from its full-AOH joint root and queried on the
certain event. Separately, a finite-law selection creates the sharp factor-two
correlated posterior from independent tags. This diagnostic is not a claim
that an arbitrary prescribed gap table is generated by CFR.
-/

import GameTheory.Analysis.ReBeL.PBSConditionedNativeGap
import GameTheory.Analysis.ReBeL.Examples.PBSJointNativeGap

noncomputable section

namespace GameTheory.ReBeL.Examples.HiddenTypes

open GameTheory.Protocol ExecutionProtocol InformationModel
open GameTheory.Math.Probability

/-- Retain the full finite legal history domain, including off-path histories. -/
local instance conditionedNativeHistoryFintype : Fintype (protocol fullPrior).History :=
  historyFintype fullPrior

/-- A nonempty actual canonical continuation, with arbitrary fixed legal
opponents, gives a well-defined query on the certain event and budget 1/8. -/
theorem pbsConditionedNativeGap_live_budget
    (opponents : Profile (fullInformation (reducedModel fullPrior)).behavioralSignature) :
    let slice := fullAOHBeliefSlice (reducedModel fullPrior) finiteBudgetControlBelief 0
    let own := fullAOHOwnLaw (reducedModel fullPrior) finiteBudgetControlBelief 0
    let t := pbsInformationBudgetRounds (reducedModel fullPrior)
      (slice.mixture own).law (fun _ => 2) 1 (1 / 8)
    let execution := pbsInformationCFRTaggedExecution (reducedModel fullPrior) slice own
      pbsRootControlFallback cfrPayoff 1 t opponents 1
    ∃ possible : ∃ point ∈ (Set.univ : Set _), point ∈ execution.support,
      (pbsInformationCFRConditionedQuery (reducedModel fullPrior) slice own
        pbsRootControlFallback cfrPayoff 1 t opponents 1 Set.univ possible).expect (fun pair =>
          |pbsInformationCFRConditionalDrawGap (reducedModel fullPrior) slice own
            pbsRootControlFallback cfrPayoff 1 t pair.2 pair.1|) ≤ 1 / 8 := by
  intro slice own t execution
  obtain ⟨point, reached⟩ := execution.support_nonempty
  refine ⟨⟨point, Set.mem_univ _, reached⟩, ?_⟩
  rw [pbsInformationCFRConditionedQuery, FinDist.condOn_univ,
    pbsInformationCFRTaggedExecution_tags]
  exact pbsJointNativeGap_live_budget

end GameTheory.ReBeL.Examples.HiddenTypes

namespace GameTheory.ReBeL.Examples.JointNativeGap

open GameTheory.Math.Probability

/-- Initial seed and type are genuinely independent and uniform. -/
def selectionPrior : FinDist (Fin 2 × Fin 2) :=
  (cfrIterationLaw 2).product (cfrIterationLaw 2)

/-- A nonconstant deterministic outcome kernel emits the retained type. -/
def selectionKernel (pair : Fin 2 × Fin 2) : FinDist (Fin 2) := FinDist.pure pair.2

/-- Retain both tags through that actual outcome emission. -/
def selectionExecution : FinDist ((Fin 2 × Fin 2) × Fin 2) :=
  selectionPrior.bind (fun pair => (selectionKernel pair).map (fun outcome => (pair, outcome)))

/-- Select the event that the emitted outcome equals the retained seed. -/
def selectionEvent : Set ((Fin 2 × Fin 2) × Fin 2) := {point | point.1.1 = point.2}

/-- The selection has genuine positive mass, witnessed by a supported outcome. -/
theorem selection_possible : ∃ point ∈ selectionEvent, point ∈ selectionExecution.support := by
  refine ⟨((0, 0), 0), rfl, FinDist.prob_pos_iff.mp ?_⟩
  rw [selectionExecution, FinDist.prob_bind_map_prod]
  norm_num [selectionPrior,
    FinDist.prob_product, selectionKernel, FinDist.prob_pure_eq_ite,
    cfrIterationLaw, FinDist.prob_ofWeights, Fin.sum_univ_two]

/-- The amplification cost comes from the ACTUAL event mass 1/2. -/
theorem selection_probability : selectionExecution.probOf selectionEvent = 1 / 2 := by
  classical
  rw [← FinDist.expect_indicator_eq_probOf]
  calc
    _ = selectionPrior.expect diagonalLoss := by
      rw [selectionExecution, FinDist.expect_bind]
      apply FinDist.expect_congr
      intro pair _
      by_cases equal : pair.1 = pair.2 <;>
        simp [selectionKernel, selectionEvent, diagonalLoss, equal]
    _ = _ := diagonalQuery_mean_control.1

/-- Conditioning, not an arbitrarily supplied query, produces the diagonal law. -/
theorem selection_query :
    (selectionExecution.condOn selectionEvent selection_possible).map Prod.fst =
      diagonalQuery := by
  classical
  have executionProb (pair : Fin 2 × Fin 2) (outcome : Fin 2) :
      selectionExecution.prob (pair, outcome) =
        selectionPrior.prob pair * (selectionKernel pair).prob outcome := by
    rw [selectionExecution, FinDist.prob_bind_map_prod]
  apply FinDist.ext_of_prob
  rintro ⟨n, type⟩
  fin_cases n <;> fin_cases type <;>
    simp only [FinDist.prob_map, FinDist.expect_eq_sum, Fintype.sum_prod_type,
      Fin.sum_univ_two, FinDist.prob_condOn, selection_probability] <;>
    norm_num [executionProb, selectionPrior, FinDist.prob_product,
      selectionKernel, FinDist.prob_pure_eq_ite, selectionEvent,
      diagonalQuery, FinDist.prob_map, FinDist.expect_eq_sum,
      Fin.sum_univ_two, cfrIterationLaw, FinDist.prob_ofWeights]

/-- The conditional loss is one although the original mean is one half.
The reciprocal event penalty is sharp, and equal marginals do not remove it. -/
theorem selection_sharp :
    selectionPrior.expect diagonalLoss = 1 / 2 ∧
      ((selectionExecution.condOn selectionEvent selection_possible).map Prod.fst).expect
        diagonalLoss = 1 := by
  rw [selection_query]
  exact diagonalQuery_mean_control

/-- It is unsound to reuse the unconditioned native-mean coefficient after
selection, even when both posterior marginals equal their original marginals. -/
theorem selection_not_unconditional_bound :
    ¬ ((selectionExecution.condOn selectionEvent selection_possible).map Prod.fst).expect
      diagonalLoss ≤ selectionPrior.expect diagonalLoss := by
  rw [selection_query]
  exact diagonalQuery_not_product_bound

/-- An impossible event cannot be given a fabricated normalized query. -/
theorem selection_impossible_event :
    ¬ ∃ point ∈ (∅ : Set ((Fin 2 × Fin 2) × Fin 2)), point ∈ selectionExecution.support := by
  rintro ⟨point, impossible, _⟩
  exact Set.notMem_empty point impossible

end GameTheory.ReBeL.Examples.JointNativeGap

namespace GameTheory.ReBeL.Examples.HiddenTypes

open GameTheory.Protocol ExecutionProtocol InformationModel
open GameTheory.Math.Probability

/-- Retain every legal history, including histories outside current support. -/
local instance publicPosteriorHistoryFintype : Fintype (protocol fullPrior).History :=
  historyFintype fullPrior

/-- A positive public observation from a real two-iterate, one-step execution
has exactly the canonical averaged-execution PBS. No posterior is supplied. -/
theorem pbsPublicPosterior_live
    (opponents : Profile (fullInformation (reducedModel fullPrior)).behavioralSignature) :
    let M := reducedModel fullPrior
    let slice := fullAOHBeliefSlice M finiteBudgetControlBelief 0
    let own := fullAOHOwnLaw M finiteBudgetControlBelief 0
    let execution := pbsInformationCFRTaggedExecution M slice own
      pbsRootControlFallback cfrPayoff 1 2 opponents 1
    ∃ next, ∃ possible : ∃ point ∈ pbsInformationCFRPublicEvent M next,
      point ∈ execution.support,
      (execution.condOn (pbsInformationCFRPublicEvent M next) possible).map Prod.snd =
        (PublicBelief.condition (S := (fullInformation M).toInfoSignals)
          (PublicBelief.continuationLaw (fullInformation M)
            (Profile.update opponents 0
              (pbsInformationCFR M (slice.mixture own) pbsRootControlFallback cfrPayoff 1 2 0))
            1 (slice.mixture own)) next
          ((pbsInformationCFR_public_possible_iff M slice own pbsRootControlFallback cfrPayoff
            1 2 opponents 1 next).mp possible)).law := by
  intro M slice own execution
  obtain ⟨point, reached⟩ := execution.support_nonempty
  refine ⟨publicTrace (fullInformation M).toInfoSignals point.2.trace,
    ⟨point, rfl, reached⟩, ?_⟩
  exact pbsInformationCFR_public_posterior_history M slice own pbsRootControlFallback
    cfrPayoff 1 2 opponents 1 _ _

end GameTheory.ReBeL.Examples.HiddenTypes

namespace GameTheory.ReBeL.Examples.JointNativeGap

open GameTheory.Math.Probability

/-- The emitted output is nonconstant and uniform after the hidden tags are
forgotten. This projection is many-to-one on the complete tagged carrier. -/
theorem selection_history : selectionExecution.map Prod.snd = cfrIterationLaw 2 := by
  calc
    selectionExecution.map Prod.snd = selectionPrior.map Prod.snd := by
      rw [selectionExecution, FinDist.map_bind, FinDist.map_eq_bind Prod.snd selectionPrior]
      apply FinDist.bind_congr
      intro pair _
      simp only [selectionKernel, FinDist.map_pure]
    _ = _ := FinDist.map_snd_product (cfrIterationLaw 2) (cfrIterationLaw 2)

/-- Output zero has genuine mass; the witness uses the actual execution. -/
theorem selection_output_zero_possible :
    ∃ point ∈ Prod.snd ⁻¹' ({0} : Set (Fin 2)), point ∈ selectionExecution.support := by
  refine ⟨((0, 0), 0), rfl, FinDist.prob_pos_iff.mp ?_⟩
  rw [selectionExecution, FinDist.prob_bind_map_prod]
  norm_num [selectionPrior, FinDist.prob_product, selectionKernel,
    FinDist.prob_pure_eq_ite, cfrIterationLaw, FinDist.prob_ofWeights, Fin.sum_univ_two]

/-- A nontrivial visible event has probability one half, not an assumed floor. -/
theorem selection_output_zero_mass :
    selectionExecution.probOf (Prod.snd ⁻¹' ({0} : Set (Fin 2))) = 1 / 2 := by
  rw [← FinDist.prob_map_eq_probOf_preimage_singleton, selection_history]
  norm_num [cfrIterationLaw, FinDist.prob_ofWeights, Fin.sum_univ_two]

/-- Projecting the conditioned execution yields the actual observed output,
while the unconditioned output law was uniform. -/
theorem selection_output_zero_posterior :
    (selectionExecution.condOn (Prod.snd ⁻¹' ({0} : Set (Fin 2)))
      selection_output_zero_possible).map Prod.snd = FinDist.pure 0 := by
  rw [FinDist.map_condOn_preimage]
  apply FinDist.eq_pure_of_support_subset_singleton
  intro output reached
  exact (FinDist.support_condOn _ _ _ reached).1

/-- Selecting a hidden bit cannot be represented by ANY event of a constant
public observation. The preimage hypothesis of the bridge is indispensable. -/
theorem hidden_selection_not_public :
    ¬ ∃ event : Set Unit, ({0} : Set (Fin 2)) = (fun _ : Fin 2 => ()) ⁻¹' event := by
  rintro ⟨event, same⟩
  have zero : (0 : Fin 2) ∈ (fun _ : Fin 2 => ()) ⁻¹' event := by
    rw [← same]
    exact Set.mem_singleton (0 : Fin 2)
  have one : (1 : Fin 2) ∈ (fun _ : Fin 2 => ()) ⁻¹' event := zero
  have impossible : (1 : Fin 2) ∈ ({0} : Set (Fin 2)) := by
    rw [same]
    exact one
  norm_num at impossible

/-- A zero-mass visible output has no supported preimage, even when the
projection's carrier includes that output. -/
theorem absent_output_has_no_posterior :
    ¬ ∃ point ∈ Prod.snd ⁻¹' ({1} : Set (Fin 2)),
      point ∈ (FinDist.pure ((0 : Fin 2), (0 : Fin 2))).support := by
  rintro ⟨point, member, reached⟩
  rw [FinDist.mem_support_pure] at reached
  subst point
  norm_num at member

end GameTheory.ReBeL.Examples.JointNativeGap
