/-
# Actual event-selection controls

A live canonical solver is run from its full-AOH joint root and queried on the
certain event. Separately, a finite-law selection creates the sharp factor-two
correlated posterior from independent tags. This diagnostic is not a claim
that an arbitrary prescribed gap table is generated by CFR.
-/

import GameTheory.Analysis.ReBeL.PBSConditionedNativeGap
import GameTheory.Analysis.ReBeL.Examples.PBSJointNativeGap

noncomputable section

namespace GameTheory.ReBeL.Examples.HiddenTypes

open GameTheory.Protocol ExecutionProtocol InformationModel
open GameTheory.Math.Probability

/-- Retain the full finite legal history domain, including off-path histories. -/
local instance conditionedNativeHistoryFintype : Fintype (protocol fullPrior).History :=
  historyFintype fullPrior

/-- A nonempty actual canonical continuation, with arbitrary fixed legal
opponents, gives a well-defined query on the certain event and budget 1/8. -/
theorem pbsConditionedNativeGap_live_budget
    (opponents : Profile (fullInformation (reducedModel fullPrior)).behavioralSignature) :
    let slice := fullAOHBeliefSlice (reducedModel fullPrior) finiteBudgetControlBelief 0
    let own := fullAOHOwnLaw (reducedModel fullPrior) finiteBudgetControlBelief 0
    let t := pbsInformationBudgetRounds (reducedModel fullPrior)
      (slice.mixture own).law (fun _ => 2) 1 (1 / 8)
    let execution := pbsInformationCFRTaggedExecution (reducedModel fullPrior) slice own
      pbsRootControlFallback cfrPayoff 1 t opponents 1
    ∃ possible : ∃ point ∈ (Set.univ : Set _), point ∈ execution.support,
      (pbsInformationCFRConditionedQuery (reducedModel fullPrior) slice own
        pbsRootControlFallback cfrPayoff 1 t opponents 1 Set.univ possible).expect (fun pair =>
          |pbsInformationCFRConditionalDrawGap (reducedModel fullPrior) slice own
            pbsRootControlFallback cfrPayoff 1 t pair.2 pair.1|) ≤ 1 / 8 := by
  intro slice own t execution
  obtain ⟨point, reached⟩ := execution.support_nonempty
  refine ⟨⟨point, Set.mem_univ _, reached⟩, ?_⟩
  rw [pbsInformationCFRConditionedQuery, FinDist.condOn_univ,
    pbsInformationCFRTaggedExecution_tags]
  exact pbsJointNativeGap_live_budget

end GameTheory.ReBeL.Examples.HiddenTypes

namespace GameTheory.ReBeL.Examples.JointNativeGap

open GameTheory.Math.Probability

/-- Initial seed and type are genuinely independent and uniform. -/
def selectionPrior : FinDist (Fin 2 × Fin 2) :=
  (cfrIterationLaw 2).product (cfrIterationLaw 2)

/-- A nonconstant deterministic outcome kernel emits the retained type. -/
def selectionKernel (pair : Fin 2 × Fin 2) : FinDist (Fin 2) := FinDist.pure pair.2

/-- Retain both tags through that actual outcome emission. -/
def selectionExecution : FinDist ((Fin 2 × Fin 2) × Fin 2) :=
  selectionPrior.bind (fun pair => (selectionKernel pair).map (fun outcome => (pair, outcome)))

/-- Select the event that the emitted outcome equals the retained seed. -/
def selectionEvent : Set ((Fin 2 × Fin 2) × Fin 2) := {point | point.1.1 = point.2}

/-- The selection has genuine positive mass, witnessed by a supported outcome. -/
theorem selection_possible : ∃ point ∈ selectionEvent, point ∈ selectionExecution.support := by
  refine ⟨((0, 0), 0), rfl, FinDist.prob_pos_iff.mp ?_⟩
  norm_num [selectionExecution, FinDist.prob_bind_map_prod, selectionPrior,
    FinDist.prob_product, selectionKernel, FinDist.prob_pure_eq_ite,
    cfrIterationLaw, FinDist.prob_ofWeights, Fin.sum_univ_two]

/-- The amplification cost comes from the ACTUAL event mass 1/2. -/
theorem selection_probability : selectionExecution.probOf selectionEvent = 1 / 2 := by
  classical
  rw [← FinDist.expect_indicator_eq_probOf]
  simpa only [selectionExecution, FinDist.expect_bind, FinDist.expect_map,
    selectionKernel, FinDist.expect_pure, selectionEvent, Set.mem_setOf_eq,
    selectionPrior, diagonalLoss] using diagonalQuery_mean_control.1

/-- Conditioning, not an arbitrarily supplied query, produces the diagonal law. -/
theorem selection_query :
    (selectionExecution.condOn selectionEvent selection_possible).map Prod.fst =
      diagonalQuery := by
  apply FinDist.ext_of_prob
  rintro ⟨n, type⟩
  fin_cases n <;> fin_cases type <;>
    norm_num [FinDist.prob_map, FinDist.expect_eq_sum, Fin.sum_univ_two,
      FinDist.prob_condOn, selection_probability, selectionExecution,
      FinDist.prob_bind_map_prod, selectionPrior, FinDist.prob_product,
      selectionKernel, FinDist.prob_pure_eq_ite, selectionEvent,
      diagonalQuery, cfrIterationLaw, FinDist.prob_ofWeights]

/-- The conditional loss is one although the original mean is one half.
The reciprocal event penalty is sharp, and equal marginals do not remove it. -/
theorem selection_sharp :
    selectionPrior.expect diagonalLoss = 1 / 2 ∧
      ((selectionExecution.condOn selectionEvent selection_possible).map Prod.fst).expect
        diagonalLoss = 1 := by
  rw [selection_query]
  exact diagonalQuery_mean_control

/-- It is unsound to reuse the unconditioned native-mean coefficient after
selection, even when both posterior marginals equal their original marginals. -/
theorem selection_not_unconditional_bound :
    ¬ ((selectionExecution.condOn selectionEvent selection_possible).map Prod.fst).expect
      diagonalLoss ≤ selectionPrior.expect diagonalLoss := by
  rw [selection_query]
  exact diagonalQuery_not_product_bound

/-- An impossible event cannot be given a fabricated normalized query. -/
theorem selection_impossible_event :
    ¬ ∃ point ∈ (∅ : Set ((Fin 2 × Fin 2) × Fin 2)), point ∈ selectionExecution.support := by
  rintro ⟨point, impossible, _⟩
  exact Set.notMem_empty point impossible

end GameTheory.ReBeL.Examples.JointNativeGap
