/-
Lint scope for the public library.

`lake lint` runs Batteries' environment linters over one module, so this
aggregator names everything the linters should see. It deliberately omits
`GameTheory.Experimental` (recorded evidence for named experiments, held to a
different bar), `GameTheory.Tests`, and the `*Test` fixtures that sit beside
their subject modules -- Mathlib likewise does not lint `MathlibTest`.

It lives outside the `GameTheory` tree so that importing `GameTheory.Analysis`
here does not breach the one-way analytic boundary the architecture audits
enforce over `GameTheory/`.

New library modules must be added here, or the linters will not see them.
-/
import GameTheory.Analysis
import GameTheory.Analysis.Approachability
import GameTheory.Analysis.Correlated
import GameTheory.Analysis.Examples
import GameTheory.Analysis.ExpectedUtility
import GameTheory.Analysis.FictitiousPlayPotential
import GameTheory.Analysis.Learning
import GameTheory.Analysis.MatrixValue
import GameTheory.Analysis.Minimax
import GameTheory.Analysis.Nash
import GameTheory.Analysis.Payoff
import GameTheory.Analysis.Protocol
import GameTheory.Analysis.Protocol.CounterfactualDecomposition
import GameTheory.Analysis.Protocol.CounterfactualReach
import GameTheory.Analysis.Protocol.CounterfactualRegret
import GameTheory.Analysis.Protocol.CounterfactualRegretMatching
import GameTheory.Analysis.Protocol.CounterfactualRootRegret
import GameTheory.Analysis.Protocol.EFG
import GameTheory.Analysis.Protocol.Examples
import GameTheory.Analysis.Protocol.Sequential
import GameTheory.Analysis.Repeated
import GameTheory.Analysis.Repeated.Examples
import GameTheory.Analysis.Repeated.Feasible
import GameTheory.Analysis.Repeated.Folk
import GameTheory.Analysis.Simplex
import GameTheory.Analysis.Stochastic
import GameTheory.Analysis.Stochastic.Discounted
import GameTheory.Analysis.Stochastic.Examples
import GameTheory.Analysis.Stochastic.Fink
import GameTheory.Analysis.TremblingHand
import GameTheory.Analysis.ZeroSumLearning
import GameTheory.Congestion
import GameTheory.Congestion.AffinePoA
import GameTheory.Congestion.Basic
import GameTheory.Congestion.Examples
import GameTheory.Congestion.Rosenthal
import GameTheory.Cooperative
import GameTheory.Cooperative.Balancedness
import GameTheory.Cooperative.Banzhaf
import GameTheory.Cooperative.Bargaining
import GameTheory.Cooperative.GaleShapley
import GameTheory.Cooperative.GaleShapley.Perfect
import GameTheory.Cooperative.Matching
import GameTheory.Cooperative.ShapleyShubik
import GameTheory.Core
import GameTheory.Core.Approximate
import GameTheory.Core.Arrow
import GameTheory.Core.BayesCorrelated
import GameTheory.Core.Bayesian
import GameTheory.Core.BayesianEquilibrium
import GameTheory.Core.BinaryCorrelated
import GameTheory.Core.BinaryMixed
import GameTheory.Core.CheapTalk
import GameTheory.Core.CheapTalkRandomization
import GameTheory.Core.Coalitional
import GameTheory.Core.CorrelatedDominance
import GameTheory.Core.Deviation
import GameTheory.Core.Equilibrium
import GameTheory.Core.FictitiousPlay
import GameTheory.Core.FictitiousPlayPotential
import GameTheory.Core.Form
import GameTheory.Core.GibbardSatterthwaite
import GameTheory.Core.Learning
import GameTheory.Core.MatrixGame
import GameTheory.Core.May
import GameTheory.Core.Mixed
import GameTheory.Core.MixedImprovement
import GameTheory.Core.MixedPotential
import GameTheory.Core.Potential
import GameTheory.Core.Preference
import GameTheory.Core.Rank
import GameTheory.Core.Rationalizability
import GameTheory.Core.Response
import GameTheory.Core.RobustWelfare
import GameTheory.Core.Shapley
import GameTheory.Core.Signature
import GameTheory.Core.SocialChoice
import GameTheory.Core.Transform
import GameTheory.Core.TremblingHand
import GameTheory.Core.Utility
import GameTheory.Core.UtilityInvariance
import GameTheory.Core.VNM
import GameTheory.Core.Welfare
import GameTheory.Core.ZeroSum
import GameTheory.Epistemic
import GameTheory.Epistemic.Agreement
import GameTheory.Epistemic.Approximate
import GameTheory.Epistemic.ApproximateAgreement
import GameTheory.Epistemic.Basic
import GameTheory.Epistemic.Knowledge
import GameTheory.Evolutionary
import GameTheory.Evolutionary.Basic
import GameTheory.Evolutionary.Mixed
import GameTheory.Evolutionary.Nash
import GameTheory.Examples.CheapTalk
import GameTheory.Examples.Classic
import GameTheory.Examples.Economic
import GameTheory.Examples.ElectronicMail
import GameTheory.Examples.FOSG
import GameTheory.Examples.Intrinsic
import GameTheory.Examples.NFG
import GameTheory.Examples.Stackelberg
import GameTheory.Examples.StochasticUniform
import GameTheory.Examples.Voting
import GameTheory.Finite.Algorithm
import GameTheory.Finite.Correctness
import GameTheory.Languages.Bayesian
import GameTheory.Languages.Bayesian.Strategic
import GameTheory.Languages.BayesianMechanism
import GameTheory.Languages.Bridges.FOSGToEFG
import GameTheory.Languages.Bridges.FOSGToEFGStrategic
import GameTheory.Languages.Bridges.NFGFOSG
import GameTheory.Languages.EFG
import GameTheory.Languages.EFG.Kuhn
import GameTheory.Languages.EFG.Strategic
import GameTheory.Languages.EFG.SubgamePerfect
import GameTheory.Languages.EFG.Zermelo
import GameTheory.Languages.FOSG
import GameTheory.Languages.FOSG.Kuhn
import GameTheory.Languages.FOSG.Values
import GameTheory.Languages.Intrinsic
import GameTheory.Languages.Intrinsic.Solution
import GameTheory.Languages.Intrinsic.Strategic
import GameTheory.Languages.MAID
import GameTheory.Languages.MAID.Basic
import GameTheory.Languages.MAID.FrontierEquivalence
import GameTheory.Languages.MAID.General
import GameTheory.Languages.MAID.ObservationPruning
import GameTheory.Languages.MAID.Order
import GameTheory.Languages.MAID.Strategic
import GameTheory.Languages.MAID.ToEFG
import GameTheory.Languages.Mechanism
import GameTheory.Languages.MultiRound
import GameTheory.Languages.MultiRound.Monitoring
import GameTheory.Languages.NFG
import GameTheory.Math
import GameTheory.Math.Approachability
import GameTheory.Math.DAG
import GameTheory.Math.Discounted
import GameTheory.Math.Eventually
import GameTheory.Math.FinRotation
import GameTheory.Math.HarmonicSequence
import GameTheory.Math.OnlineLearning
import GameTheory.Math.OrthantProjection
import GameTheory.Math.PositivePartFixedPoint
import GameTheory.Math.Probability.Bounds
import GameTheory.Math.Probability.Convergence
import GameTheory.Math.Probability.FinDist
import GameTheory.Math.Probability.Measure
import GameTheory.Math.Probability.OnlineLearning
import GameTheory.Math.Probability.Simplex
import GameTheory.Math.RegretAggregation
import GameTheory.Math.SimplexApproximation
import GameTheory.Mechanism
import GameTheory.Mechanism.AffineMaximizer
import GameTheory.Mechanism.AllPay
import GameTheory.Mechanism.Auction
import GameTheory.Mechanism.BayesianIncentives
import GameTheory.Mechanism.BayesianWelfare
import GameTheory.Mechanism.Combinatorial
import GameTheory.Mechanism.Combinatorial.Basic
import GameTheory.Mechanism.Combinatorial.QuasiField
import GameTheory.Mechanism.Combinatorial.Surplus
import GameTheory.Mechanism.FairDivision
import GameTheory.Mechanism.FairDivision.Basic
import GameTheory.Mechanism.FairDivision.RoundRobin
import GameTheory.Mechanism.FairDivision.TwoAgentEFX
import GameTheory.Mechanism.FeasiblePosteriors
import GameTheory.Mechanism.Groves
import GameTheory.Mechanism.Implementation
import GameTheory.Mechanism.InformationDesign
import GameTheory.Mechanism.JointFeasiblePosteriors
import GameTheory.Mechanism.Knapsack
import GameTheory.Mechanism.Knapsack.Aggregate
import GameTheory.Mechanism.Knapsack.Algorithm
import GameTheory.Mechanism.Knapsack.Approximation
import GameTheory.Mechanism.Knapsack.ApproximationAlgorithm
import GameTheory.Mechanism.Knapsack.ApproximationCorrectness
import GameTheory.Mechanism.Knapsack.Basic
import GameTheory.Mechanism.Knapsack.Correctness
import GameTheory.Mechanism.Knapsack.ExactBridge
import GameTheory.Mechanism.Knapsack.Mechanism
import GameTheory.Mechanism.PosteriorSignals
import GameTheory.Mechanism.PrincipalAgent
import GameTheory.Mechanism.QuasiLinear
import GameTheory.Mechanism.ReserveVickrey
import GameTheory.Mechanism.Revelation
import GameTheory.Mechanism.SingleParameter
import GameTheory.Mechanism.Strategyproof
import GameTheory.Protocol
import GameTheory.Protocol.Assessment
import GameTheory.Protocol.Backward
import GameTheory.Protocol.BehavioralAssessment
import GameTheory.Protocol.Execution
import GameTheory.Protocol.Extraction
import GameTheory.Protocol.History
import GameTheory.Protocol.Information
import GameTheory.Protocol.PolicyMeasure
import GameTheory.Protocol.Randomized
import GameTheory.Protocol.Strategic
import GameTheory.Protocol.SubgamePerfect
import GameTheory.Protocol.Tree
import GameTheory.Protocol.Zermelo
import GameTheory.Repeated
import GameTheory.Repeated.Basic
import GameTheory.Repeated.Discounted
import GameTheory.Repeated.Monitoring
import GameTheory.Repeated.MonitoringContinuation
import GameTheory.Repeated.MonitoringDecomposition
import GameTheory.Repeated.MonitoringDiscounted
import GameTheory.Repeated.MonitoringOneShot
import GameTheory.Repeated.MonitoringPayoff
import GameTheory.Repeated.MonitoringRank
import GameTheory.Repeated.MonitoringSelfGeneration
import GameTheory.Repeated.Periodic
import GameTheory.Repeated.Protocol
import GameTheory.Repeated.Trigger
import GameTheory.Repeated.Uniform
import GameTheory.Stochastic
import GameTheory.Stochastic.Basic
import GameTheory.Stochastic.FiniteHorizon
import GameTheory.Stochastic.History
import GameTheory.Stochastic.Kuhn
import GameTheory.Stochastic.PerfectMonitoring
import GameTheory.Stochastic.PublicPolicy
import GameTheory.Stochastic.Uniform
import GameTheory.Stochastic.ZeroSum
