/-
# Continuity of finite mixed expected utility

Pointwise convergence of every player's finite mixed strategy implies
convergence of expected utility.  This is the game-level consumer of the
finite-law product and expectation limits.
-/

import GameTheory.Math.Probability.Convergence
import GameTheory.Core.Mixed

noncomputable section

namespace GameTheory

open Filter GameTheory.Math.Probability

universe uι us uo

variable {ι : Type uι} [Fintype ι] [DecidableEq ι]

namespace UtilityGame

variable {G : UtilityGame.{uι, us, uo} ι}
variable [∀ i, Fintype (G.form.sig.Strategy i)]

/-- Expected utility in the finite mixed extension is continuous under
coordinatewise pointwise convergence of canonical finite laws. -/
theorem expectedUtility_mixed_tendsto
    {sequence : ℕ → Profile G.form.sig.mixed}
    {target : Profile G.form.sig.mixed}
    (hconverges : ∀ i, FinDistConvergesPointwise
      (fun n => sequence n i) (target i)) (who : ι) :
    Tendsto
      (fun n => expectedUtility G.utility who (G.form.mixed.play (sequence n)))
      atTop
      (nhds (expectedUtility G.utility who (G.form.mixed.play target))) := by
  have hproduct := FinDistConvergesPointwise.pi hconverges
  have hexpect := hproduct.expect
    (fun profile => expectedUtility G.utility who (G.form.play profile))
  simpa only [GameForm.mixed_play, expectedUtility_bind] using hexpect

/-- Fixing one player's pure action preserves convergence of the expected
utility generated by the remaining convergent mixed strategies. -/
theorem expectedUtility_update_pure_tendsto
    {sequence : ℕ → Profile G.form.sig.mixed}
    {target : Profile G.form.sig.mixed}
    (hconverges : ∀ i, FinDistConvergesPointwise
      (fun n => sequence n i) (target i)) (who : ι)
    (action : G.form.sig.Strategy who) :
    Tendsto
      (fun n => expectedUtility G.utility who
        (G.form.mixed.play
          (Profile.update (sequence n) who (FinDist.pure action))))
      atTop
      (nhds (expectedUtility G.utility who
        (G.form.mixed.play
          (Profile.update target who (FinDist.pure action))))) := by
  apply expectedUtility_mixed_tendsto
  intro other
  by_cases hother : other = who
  · subst hother
    simp only [Profile.update_same]
    exact finDistConvergesPointwise_const _
  · simp only [Profile.update_of_ne _ _ hother]
    exact hconverges other

end UtilityGame

end GameTheory
