/-
# Analytic ReBeL proof surface

This opt-in root keeps analytic imports in the architecture-owned Analysis
surface. All declarations retain the GameTheory.ReBeL namespace and reuse
canonical Protocol execution and information, rather than a parallel model.
-/

import GameTheory.Analysis.ReBeL.LocalRegret
import GameTheory.Analysis.ReBeL.Examples.LocalRegret
import GameTheory.Analysis.ReBeL.ChronologicalLocality
import GameTheory.Analysis.ReBeL.Examples.ChronologicalLocality
import GameTheory.Analysis.ReBeL.PolicyPatching
import GameTheory.Analysis.ReBeL.RootDecomposition
import GameTheory.Analysis.ReBeL.Examples.RootDecomposition
import GameTheory.Analysis.ReBeL.RegretMatching
import GameTheory.Analysis.ReBeL.CFRTrace
import GameTheory.Analysis.ReBeL.PayoffBounds
import GameTheory.Analysis.ReBeL.RootRegretBounds
import GameTheory.Analysis.ReBeL.WeightedAverage
import GameTheory.Analysis.ReBeL.OwnReachAverage
import GameTheory.Analysis.ReBeL.OutcomeReach
import GameTheory.Analysis.ReBeL.IndependentRealization
import GameTheory.Analysis.ReBeL.UnilateralAverage
import GameTheory.Analysis.ReBeL.AverageNash
import GameTheory.Analysis.ReBeL.CFRNash
import GameTheory.Analysis.ReBeL.Examples.CFRNash
import GameTheory.Analysis.ReBeL.RationalArithmetic
import GameTheory.Analysis.ReBeL.RationalEvaluation
import GameTheory.Analysis.ReBeL.RationalReach
import GameTheory.Analysis.ReBeL.RationalCounterfactual
import GameTheory.Analysis.ReBeL.RationalIteration
import GameTheory.Analysis.ReBeL.RationalAverage
import GameTheory.Analysis.ReBeL.Examples.RationalCodec
import GameTheory.Analysis.ReBeL.Examples.RationalInformation
import GameTheory.Analysis.ReBeL.Examples.RationalPrimitives
import GameTheory.Analysis.ReBeL.Examples.RationalChance
import GameTheory.Analysis.ReBeL.Examples.RationalExecution
import GameTheory.Analysis.ReBeL.Examples.RationalReach
import GameTheory.Analysis.ReBeL.Examples.RationalSites
import GameTheory.Analysis.ReBeL.Examples.RationalCounterfactual
import GameTheory.Analysis.ReBeL.Examples.RationalProjection
import GameTheory.Analysis.ReBeL.RationalMatching
import GameTheory.Analysis.ReBeL.Examples.RationalRegret
import GameTheory.Analysis.ReBeL.Examples.RationalIteration
import GameTheory.Analysis.ReBeL.RationalAverageEquiv
import GameTheory.Analysis.ReBeL.Examples.RationalAverage
import GameTheory.Analysis.ReBeL.EquilibriumValue
import GameTheory.Analysis.ReBeL.Examples.EquilibriumValue
import GameTheory.Analysis.ReBeL.ValueEnvelope
import GameTheory.Analysis.ReBeL.ValuePlans
import GameTheory.Analysis.ReBeL.TypeValue
import GameTheory.Analysis.ReBeL.ValueGeometry
import GameTheory.Analysis.ReBeL.ContinuationConsistency
import GameTheory.Analysis.ReBeL.ContinuationRealization
import GameTheory.Analysis.ReBeL.ValueEnvelopeBridge
import GameTheory.Analysis.ReBeL.Examples.ValueRadial
import GameTheory.Analysis.ReBeL.ValueKink
import GameTheory.Analysis.ReBeL.ValueDeviations
import GameTheory.Analysis.ReBeL.ContinuationDeviations
import GameTheory.Analysis.ReBeL.BeliefExistence
import GameTheory.Analysis.ReBeL.RootTypeMemory
import GameTheory.Analysis.ReBeL.Examples.ValueGeometry
import GameTheory.Analysis.ReBeL.TypeBeliefSlice
import GameTheory.Analysis.ReBeL.PBSInfoValue
import GameTheory.Analysis.ReBeL.PBSValue
import GameTheory.Analysis.ReBeL.PBSGeometry
import GameTheory.Analysis.ReBeL.PBSOptimality
import GameTheory.Analysis.ReBeL.PBSFullAOH
import GameTheory.Analysis.ReBeL.ValueDifferential
import GameTheory.Analysis.ReBeL.PBSTheorem1
import GameTheory.Analysis.ReBeL.Examples.ValuePBS
import GameTheory.Analysis.ReBeL.CFRDTrace
import GameTheory.Analysis.ReBeL.CFRDRegret
import GameTheory.Analysis.ReBeL.DominatingReach
import GameTheory.Analysis.ReBeL.CFRDProbe
import GameTheory.Analysis.ReBeL.CFRDCutBackup
import GameTheory.Analysis.ReBeL.CFRDCutDriver
import GameTheory.Analysis.ReBeL.CFRDPrefix
import GameTheory.Analysis.ReBeL.CFRDTrunkRegret
import GameTheory.Analysis.ReBeL.CFRDLeafContract
import GameTheory.Analysis.ReBeL.CFRDRootRegret
import GameTheory.Analysis.ReBeL.CFRDNash
import GameTheory.Analysis.ReBeL.CFRDConstants
import GameTheory.Analysis.ReBeL.CFRDSafety
import GameTheory.Analysis.ReBeL.CFRDPBSOracle
import GameTheory.Analysis.ReBeL.CFRDSearch
import GameTheory.Analysis.ReBeL.CFRDCarriedPlay
import GameTheory.Analysis.ReBeL.Examples.CFRDExecution
import GameTheory.Analysis.ReBeL.Examples.CFRDUniformControl
import GameTheory.Analysis.ReBeL.Examples.CFRDSeedControl
import GameTheory.Analysis.ReBeL.PBSLeafOptimality
import GameTheory.Analysis.ReBeL.Examples.CFRDLiveControl
import GameTheory.Analysis.ReBeL.CFRDResolve
import GameTheory.Analysis.ReBeL.CFRDResolveSafety
import GameTheory.Analysis.ReBeL.Examples.CFRDResolveControl
import GameTheory.Analysis.ReBeL.Examples.CFRDResolveNegative
import GameTheory.Analysis.ReBeL.CFRDResolveBelief
import GameTheory.Analysis.ReBeL.CFRDRecursivePlay
import GameTheory.Analysis.ReBeL.Examples.CFRDEquilibriumReplacement
import GameTheory.Analysis.ReBeL.CFRDDelayedSampling
import GameTheory.Analysis.ReBeL.CFRDChildResolve
import GameTheory.Analysis.ReBeL.CFRDChildOracle
import GameTheory.Analysis.ReBeL.Examples.CFRDChildControl
import GameTheory.Analysis.ReBeL.CFRDZeroReachCompletion
import GameTheory.Analysis.ReBeL.Examples.CFRDZeroReachControl
import GameTheory.Analysis.ReBeL.CFRDZeroReachOptimality
import GameTheory.Analysis.ReBeL.CFRDZeroReachContinuation
import GameTheory.Analysis.ReBeL.CFRDCompletedLeaf
import GameTheory.Analysis.ReBeL.CFRDConditionalCompletion
import GameTheory.Analysis.ReBeL.CFRDQuerySupport
import GameTheory.Analysis.ReBeL.CFRDCompletedContract
import GameTheory.Analysis.ReBeL.CFRDPublicSplice
import GameTheory.Analysis.ReBeL.CFRDPublicResponse
import GameTheory.Analysis.ReBeL.Examples.CFRDPublicSplice
import GameTheory.Analysis.ReBeL.CFRDReferenceSlice
import GameTheory.Analysis.ReBeL.CFRDFactualChild
import GameTheory.Analysis.ReBeL.Examples.CFRDFactualChild
import GameTheory.Analysis.ReBeL.CFRDFactualQuery
import GameTheory.Analysis.ReBeL.CFRDFactualMixture
import GameTheory.Analysis.ReBeL.CFRDClamp
import GameTheory.Analysis.ReBeL.CFRDExactDriver
import GameTheory.Analysis.ReBeL.CFRDExactSafety
import GameTheory.Analysis.ReBeL.Examples.CFRDExactDriver
import GameTheory.Analysis.ReBeL.CFRDNoisyDriver
import GameTheory.Analysis.ReBeL.PBSApproximateOptimality
import GameTheory.Analysis.ReBeL.CFRDApproximateLeaf
import GameTheory.Analysis.ReBeL.Examples.CFRDApproximateLeaf
import GameTheory.Analysis.ReBeL.FinitePlanLearning
import GameTheory.Analysis.ReBeL.FinitePlanNash
import GameTheory.Analysis.ReBeL.FinitePlanBudget
import GameTheory.Analysis.ReBeL.PBSFinitePlanSolver
import GameTheory.Math.Probability.FinDistMassFloor
import GameTheory.Analysis.ReBeL.Examples.PBSFinitePlanSolver
import GameTheory.Analysis.ReBeL.CFRDFiniteChild
import GameTheory.Analysis.ReBeL.CFRDFiniteContinuation
import GameTheory.Analysis.ReBeL.CFRDFiniteDriver
import GameTheory.Analysis.ReBeL.Examples.CFRDFiniteChild
import GameTheory.Analysis.ReBeL.CFRDRefreshMix
import GameTheory.Analysis.ReBeL.CFRDFiniteRefresh
import GameTheory.Analysis.ReBeL.CFRDFiniteRefreshSafety
import GameTheory.Analysis.ReBeL.Examples.CFRDFiniteRefresh
import GameTheory.Analysis.ReBeL.CFRDResolveEnvelope
import GameTheory.Analysis.ReBeL.CFRDEnvelopeSafety
import GameTheory.Analysis.ReBeL.Examples.CFRDEnvelope
import GameTheory.Analysis.ReBeL.CFRDCoherentDraw
import GameTheory.Analysis.ReBeL.CFRDFiniteCoherent
import GameTheory.Analysis.ReBeL.Examples.CFRDCoherentDraw
import GameTheory.Analysis.ReBeL.CFRDCoherentStages
import GameTheory.Analysis.ReBeL.Examples.CFRDCoherentStages
